- flate/flate_test.go
- flate/gen.go
- flate/huffman_bit_writer.go
- flate/huffman_code.go
- flate/inflate.go
> Merge changes from go tip. Fix go bug #11030.

- LICENSE
- README.md
> Relicense to Go (BSD) license.

- flate/huffman_bit_writer.go
It was not really faster, and this is more readable.
> Remove zero-by-copying. 

- README.md
- flate/deflate.go
- flate/snappy.go
Ports https://github.com/golang/go/issues/18625
> Reduce stack pressure due to array copies

- .travis.yml
- README.md
- compressible.go
- compressible_test.go
> Add compressibility estimater.

- zstd/decoder.go
- zstd/decoder_test.go
Fix problem with byte buffer shortcut not returning correct data when input is a small *bytes.Buffer and add test for these.
Fixes #115
> Fix Reset deadlock/problems with bytes.Buffer

- zstd/decoder.go
- zstd/decoder_test.go
> Fix race when creating decoder stream

- zstd/enc_dfast.go
~Tweak hashing similar to : https://github.com/facebook/zstd/pull/1681~
Tweak post-match hashing to do:
* match `start+1` (long)
* match `start+2` (short)
* match `end-2` (long)
* match `end-1` (short)
Allow switching between different repeats.
before/after:
```
silesia.tar	zskp	2	211947520	67666622	1605	125.86
silesia.tar	zskp	2	211947520	67546473	1579	127.93
consensus.db.10gb	zskp	2	10737418240	3991229575	70470	145.31
consensus.db.10gb	zskp	2	10737418240	3990902566	68423	149.66
enwik9	zskp	2	1000000000	317607926	7984	119.45
enwik9	zskp	2	1000000000	317492170	7932	120.23
gob-stream	zskp	2	1911399616	208520333	6748	270.13
gob-stream	zskp	2	1911399616	208014379	6705	271.86
silesia.tar	zskp	2	211947520	67666622	1605	125.86
silesia.tar	zskp	2	211947520	67546473	1579	127.93
10gb.tar	zskp	2 …
```
> zstd: Tweak encoder hashing+repeating

- README.md
- s2/README.md
- s2/cmd/s2c/main.go
- s2/cmd/s2d/main.go
Add option to remove input files and option to disable output.
> Add 'remove' and 'quiet' flags

- s2/encode.go
When using ReadFrom, avoid a memcopy by reading directly into the compression buffer.
> S2: Avoid memcopy in ReadFrom

- fse/fse_test.go
> Remove cmp dependency

- .travis.yml
- go.mod
> Add empty Go mod file

- zstd/snappy_test.go
> test: Fix benchmark leaking decoder

- zstd/decoder.go
- zstd/encoder_options.go
> Fix zstd documentation

- zstd/encoder_options.go
Double window size for default (8MB)
4x for Better (16 MB)
> zstd: Adjust default window sizes

- zstd/decoder.go
> zstd: Reduce allocations when decoding from a bytes.Buffer

- s2/cmd/s2c/main.go
- s2/cmd/s2d/main.go
Make sure we flush everything we've got before shutting down.
> s2c: Handle sigint better

- .travis.yml
> test: Update Go CI to 1.15

- zstd/encoder_options.go
> zstd: Set allLitEntropy true in default configuration

- s2/encode.go
- s2/encode_test.go
- zstd/enc_better.go
Add uncompressed stream option which only does uncompressed blocks with CRC.
Diversify regression tests.
> s2: Add uncompressed stream option

- s2/cmd/s2c/main.go
- s2/cmd/s2d/main.go
Always exit if commands have help flag.
> s2: Exit commands on help

- s2/encode_test.go
- s2/s2_test.go
Add benchmark with random stream compression.
> tests: Add random data stream compression

- .travis.yml
Experiment to exclude all except master
> tests: Only build master

- s2/cmd/s2c/main.go
> Fix s2c output

- zstd/encoder_test.go
> test: Extend test timeout

- s2/_generate/gen.go
- s2/encodeblock_amd64.s
Fixes rare crash on amd64.
Fixes #361
> s2: Load after checking src limit on amd64.

- flate/reader_test.go
- flate/writer_test.go
- zstd/README.md
- zstd/zip_test.go
> doc: Update zstd inside zip

- gzhttp/README.md
- gzhttp/gzip.go
- gzhttp/gzip_test.go
- gzhttp/transport_test.go
> gzhttp: Reduce allocs more

- gzhttp/gzip.go
- gzhttp/gzip_test.go
Set on any response to disable compression.
> gzhttp: Add header to skip compression

- LICENSE
- zstd/internal/xxhash/xxhash.go
- zstd/internal/xxhash/xxhash_amd64.go
- zstd/internal/xxhash/xxhash_amd64.s
Includes https://github.com/cespare/xxhash/issues/54
Fixes #248
> Upgrade xxhash

- gzip/gzip_test.go
> Add performance baseline

- flate/fast_encoder.go
> flate: Up to 5% faster encoding

- huff0/decompress.go
> huff0: Faster 1X Decompression

- flate/huffman_bit_writer.go
It is extremely unlikely that predefined codes are better when there are multiple tokens (verified by tests)
Skip checks if there is 250 or more tokens.
> flate: Skip predef checks if many tokens

- zstd/zip.go
Now that decoding is stateless we can pool decoders.
> zstd: Reuse zip decoders

- zstd/decoder_test.go
Factored out common code for benchmark decompression of files. This is used to benchmark against the Silesia corpus and Enwik9; I corrected the path from `enwik8.zst` to `enwik9.zst`.
I found this procedure useful when benchmarking against custom test files.
> tests: [zstd] Factor out common benchmark routine

- zstd/_generate/gen.go
- zstd/decoder.go
- zstd/decoder_options.go
- zstd/decoder_test.go
- zstd/framedec.go
- zstd/seqdec.go
- zstd/seqdec_amd64.go
- zstd/seqdec_amd64.s
> Enable assembly for more cases

- .github/workflows/go.yml
Adds a CI job to verify code generation is up-to-date with the repository.
> .github: check code generation

- s2/cmd/s2d/main.go
- s2/decode.go
- s2/encode_test.go
Offset sign was flipped
Fixes #574
> s2: Fix incorrect seek for io.SeekEnd

- s2/encode.go
> s2: Remove sanity load on index creation

- s2/decode.go
Will skip all CRC calculations when decoding frames.
> s2: Add ReaderIgnoreCRC

- zip/writer.go
Accidentally reverted #313 in #432
Fixes #623
> zip: Re-add zip64 fix

- .github/workflows/go.yml
- .github/workflows/release.yml
- .goreleaser.yml
Disable tests for 1.17
Update garble
> tests: Upgrade to Go 1.20

- .github/workflows/codeql-analysis.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
> ci: set minimal permissions to GitHub Workflows

- .github/workflows/release.yml
(hopefully) fixes:
```
Invalid workflow file: .github/workflows/release.yml#L13
The workflow is not valid. .github/workflows/release.yml (Line: 13, Col: 9): Unexpected value 'content'
```
> Fix Goreleaser permissions

- gzhttp/writer/gzkp/gzkp.go
- gzhttp/writer/gzstd/stdlib.go
Clamp compression levels to valid values.
> gzhttp: Clamp compression level

- s2/writer.go
> s2: Fix up AddSkippableBlock more

- .github/workflows/release.yml
- .goreleaser.yml
Let's see how bad things are without garble.
> build: Remove garble compiler

- internal/fuzz/helpers.go
- s2/fuzz_test.go
- s2/reader.go
When DecodeConcurrent encounters an error it can lock up in some cases.
Fix and add fuzz test for stream decoding.
Fixes #920
> s2: Fix DecodeConcurrent deadlock on errors

- ossfuzz/ossfuzz.sh
Replace until https://github.com/AdamKorcz/go-118-fuzz-build/pull/24 is merged.
> ci: Add testing replacement
