- flate/crc32_amd64.go
- flate/crc32_amd64.s
- flate/crc32_noasm.go
- flate/deflate.go
- flate/deflate_test.go
- flate/huffman_bit_writer.go
- flate/huffman_code.go
- flate/reader_test.go
- flate/writer_test.go
- gzip/gzip.go
- gzip/gzip_test.go
- zlib/writer.go
- zlib/writer_test.go
Add encoder that does not attempt to do any back-matches. This gives much more predictable performance, but at a big compression size cost. Performance is currently approximately ~70MB/s.
Use level = ConstantCompression (-2) to enable.
> Constant time encoder

- README.md
- flate/deflate.go
- flate/snappy.go
Add fast skipping on consecutive missed matches. ~2x-10x as fast on precompressed/uncompressible content.
If there is more than X consecutive match failures, it will start skipping bytes. The number of bytes required and the number of bytes skipped is dependent on the compression level.
Level 1, random bytes: Before: 56.13MB/s. After: 139.54MB/s.
> Fast skipping on long non-matches.

- flate/inflate.go
- flate/inflate_test.go
- gzip/gunzip.go
- gzip/gunzip_test.go
Add io.WriterTo support for gzip and inflate - nice speedup with io.Copy():
```
BenchmarkGunzipCopy-8                 30          42202413 ns/op         117.57 MB/s
BenchmarkGunzipNoWriteTo-8            30          42469096 ns/op         116.83 MB/s
BenchmarkGunzipStdlib-8               30          49636173 ns/op          99.96 MB/s
```
> Add io.WriterTo support

- README.md
- zip/example_test.go
- zip/reader.go
- zip/writer.go
Implement setting the compression level for a zip archive by registering
a per-Writer compressor through Writer.RegisterCompressor.  If no
compressors are registered, fall back to the ones registered at the
package level.  Also implements per-Reader decompressors.
Contributed by Colin Cross,
Source: https://go-review.googlesource.com/#/c/16669/4
> CL16669: archive/zip: enable overriding (de)compressors per file

- README.md
- flate/deflate.go
- flate/deflate_test.go
Errors from the underlying writer was not being forwarded/returned, so that is now done, and tests have been added to test that functionality.
Fixes #15
> Fix error propagation

- flate/token.go
Switch statements cannot be inlined. If statements can. Reference:
golang/go#7655
golang/go#13071
```
BenchmarkEncodeDigitsSpeed1e4-4        52.22        53.77        1.03x
BenchmarkEncodeDigitsSpeed1e5-4        55.01        57.05        1.04x
BenchmarkEncodeDigitsSpeed1e6-4        54.36        57.03        1.05x
BenchmarkEncodeDigitsDefault1e4-4      20.33        20.38        1.00x
BenchmarkEncodeDigitsDefault1e5-4      11.65        11.71        1.01x
BenchmarkEncodeDigitsDefault1e6-4      10.68        10.78        1.01x
BenchmarkEncodeDigitsCompress1e4-4     20.38        20.77        1.02x
BenchmarkEncodeDigitsCompress1e5-4     11.65        11.85        1.02x
BenchmarkEncodeDigitsCompress1e6-4     10.76        10.97        1.02x
BenchmarkEncodeTwainSpeed1e4-4         46.40        47.77 …
```
> Convert switch block to if block

- flate/crc32_amd64.s
Not sure if it is worth it.
Benchstat results:
Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz:
```
name                       old time/op    new time/op    delta
EncodeDigitsConstant1e4-4    49.6µs ± 2%    48.8µs ± 1%  -1.80%  (p=0.008 n=5+5)
EncodeDigitsConstant1e5-4     467µs ± 1%     460µs ± 1%    ~     (p=0.056 n=5+5)
EncodeDigitsConstant1e6-4    4.67ms ± 0%    4.61ms ± 1%  -1.45%  (p=0.008 n=5+5)
EncodeDigitsSpeed1e4-4        182µs ± 0%     182µs ± 0%    ~     (p=0.841 n=5+5)
EncodeDigitsSpeed1e5-4       1.67ms ± 1%    1.68ms ± 1%    ~     (p=0.222 n=5+5)
EncodeDigitsSpeed1e6-4       16.8ms ± 3%    16.6ms ± 1%    ~     (p=0.421 n=5+5)
EncodeDigitsDefault1e4-4      364µs ± 0%     364µs ± 0%    ~     (p=1.000 n=5+5)
EncodeDigitsDefault1e5-4     5.04ms ± 1%    5.03ms ± 1%    ~     (p=0.841 …
```
> Make histogram function faster

- README.md
- flate/crc32_amd64.s
- flate/deflate_test.go
When length was 7, an extra byte would be read from the input. In rare cases that would hit a page boundary when flushing and crash.
The test has been extended to increase the chance of detecting a situation like this.
Fixes #20
> Fix out of bounds read

- flate/crc32_amd64.go
- flate/deflate.go
- flate/deflate_test.go
3-5% on no assembly. 1-3% with assembly.
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkEncodeDigitsDefault1e4-8      392822        385422        -1.88%
BenchmarkEncodeDigitsDefault1e5-8      5360306       5160295       -3.73%
BenchmarkEncodeDigitsDefault1e6-8      56553235      54469783      -3.68%
BenchmarkEncodeDigitsCompress1e4-8     387022        383421        -0.93%
BenchmarkEncodeDigitsCompress1e5-8     5310303       5143627       -3.14%
BenchmarkEncodeDigitsCompress1e6-8     55203155      55003143      -0.36%
BenchmarkEncodeTwainDefault1e4-8       431358        427024        -1.00%
BenchmarkEncodeTwainDefault1e5-8       5910338       5837000       -1.24%
BenchmarkEncodeTwainDefault1e6-8       61903540      61103495      -1.29% …
```
> Split encode functions, so hash and match length can be inlined.

- flate/deflate.go
- flate/huffman_bit_writer.go
Level 1,2 and 3 will always output a dynamic Huffman table block.
We already have an uncompressed check, before we decide to use this, so we assume that storing a dynamic Huffman table will always be an improvement. Therefore we can skip bit counting for the block.
~ 4-6% faster, though depending on input.
> Skip uncompressed/static table check on level 1,2 & 3.

- flate/huffman_bit_writer.go
We don't need to zero slices and objects on reset, that are assumed to be dirty anyway.
> Remove unneeded zeroing of slices

- flate/crc32_amd64.s
There were leaks into the assembler, where it depended on RAX and RDX > 16.
This also uses REP CMPSB for remaining matches.
> Update matching assembler.

- flate/deflate.go
- flate/deflate_test.go
- flate/snappy.go
This will rebalance the compression levels to have a more even distribution of compression levels. The general trend of this is to make compression faster, which means that a given compression level (except 1 and 9) will be faster.
The existing implementation favors compression, and from level 5 and up, very small compresssion improvements are added for very high computation cost.
Rough guidelines: Previous level 3 speed is now equal to level 6.
New default is level 5, which in most cases offers a quite good compression, without getting diminished returns from additional computation power.
See "rebalance" tabs for benchmarks of rebalanced levels:
https://docs.google.com/spreadsheets/d/1nuNE2nPfuINCZJRMt6wFWhKpToF95I47XjSsc-1rbPQ/edit?usp=sharing
> Rebalance compression levels.

- flate/huffman_bit_writer.go
Optimize bitwriter, by eliminating some nil checks and use a simpler test to determine the token type.
```
name                       old time/op    new time/op    delta
EncodeDigitsConstant1e4-4   159MB/s ± 0%   184MB/s ± 2%  +15.30%
EncodeDigitsConstant1e5-4   173MB/s ± 0%   186MB/s ± 7%   +7.21%
EncodeDigitsConstant1e6-4   171MB/s ± 0%   195MB/s ± 1%  +13.94%
EncodeDigitsSpeed1e4-4     45.4MB/s ± 1%  47.5MB/s ± 2%   +4.60%
EncodeDigitsSpeed1e5-4     70.5MB/s ± 0%  71.7MB/s ± 2%   +1.72%
EncodeDigitsSpeed1e6-4      110MB/s ± 0%   118MB/s ± 0%   +7.96%
EncodeDigitsDefault1e4-4   26.6MB/s ± 0%  26.3MB/s ± 0%   -0.83%
EncodeDigitsDefault1e5-4   21.3MB/s ± 1%  22.0MB/s ± 0%   +3.00%
EncodeDigitsDefault1e6-4   19.7MB/s ± 0%  21.2MB/s ± 0%   +8.03%
EncodeDigitsCompress1e4-4  22.9MB/s ± 1% …
```
> Optimize bitwriter code lookups

- README.md
I propose this file change to clarify that this modification still makes the output compatible with existing tools. It wasn't apparent to me at first read, and I double-checked with a couple of colleagues.
> Clarify that snappy is still gzip compatible

- flate/deflate.go
Always at least attempt to Huffman compress the blocks.
Since this part is now used for level 4-7, we can afford some more expensive checks. This should make base64 encoding of random input better.
Also, use variable threshold, instead of constant 10 literals.
> Level 4-7: Always attempt Huffman

- flate/snappy.go
No measurable impact, but simplifies handling.
> Use a minimum offset to avoid subtracting and adding 1 to indexes.

- flate/crc32_amd64.s
- snappy/asm_amd64.s
It was correct for the *_amd64.go files, just not the *_amd64.s files,
which used OR instead of AND.
See the "Build Constraints" section of https://golang.org/pkg/go/build/
> Fix (!noasm AND !appengine) build tag.

- flate/crc32_amd64.s
- snappy/asm_amd64.s
runtime/textflag.h defines:
NOPROF  1
DUPOK   2
NOSPLIT 4
The DUPOK bit was why the bug in
https://github.com/klauspost/compress/commit/6ea72a38a8cdbe25966059c547d425e580c624a7
wasn't picked up earlier.
The existing 7 is presumably a copy/paste of some standard library asm
code. It's a legacy idiom that really should be 5 or 4. See
https://groups.google.com/d/msg/golang-nuts/uJTYuruvnZM/6j4KXgkdcf0J for
some history.
Asm code in the standard library uses NOSPLIT instead of 4 these days.
> Remove DUPOK and NOPROF flags from asm functions.

- flate/crc32_amd64.go
- flate/crc32_amd64.s
It's also simpler, in that it doesn't use SSE any more.
name                       old speed      new speed      delta
EncodeDigitsDefault1e4-8   39.1MB/s ± 0%  39.9MB/s ± 0%  +1.89%  (p=0.016 n=4+5)
EncodeDigitsDefault1e5-8   30.9MB/s ± 0%  31.8MB/s ± 0%  +2.92%  (p=0.008 n=5+5)
EncodeDigitsDefault1e6-8   29.7MB/s ± 1%  30.6MB/s ± 0%  +3.04%  (p=0.008 n=5+5)
EncodeDigitsCompress1e4-8  33.3MB/s ± 0%  33.8MB/s ± 0%  +1.49%  (p=0.008 n=5+5)
EncodeDigitsCompress1e5-8  23.7MB/s ± 0%  24.2MB/s ± 1%  +2.23%  (p=0.008 n=5+5)
EncodeDigitsCompress1e6-8  22.4MB/s ± 0%  22.9MB/s ± 1%  +2.05%  (p=0.008 n=5+5)
EncodeTwainDefault1e4-8    37.4MB/s ± 0%  38.1MB/s ± 0%  +1.93%  (p=0.016 n=4+5)
EncodeTwainDefault1e5-8    39.3MB/s ± 1%  40.4MB/s ± 1%  +2.85%  (p=0.008 n=5+5)
EncodeTwainDefault1e6-8 …
> Optimize the matchLenSSE4 asm implementation.

- flate/deflate.go
- flate/deflate_test.go
- flate/snappy.go
- flate/token.go
Rewrite level 1 to a new level 2, that can do cross-block matching.
This provides a speedup to level 2+3 and rebalances level 4-7 accordingly.
AMD64, 1 core used.
"Level", "Gzipped size", "Throughput". 
Web content (sites, 481601400 bytes):
```
1, 165556800 bytes, 71.96MB/s
2, 163167700 bytes, 70.18MB/s
3, 162457100 bytes, 66.70MB/s 
```
enwik9 (1000000000 bytes):
```
1,  391052014 bytes, 78.36 MB/s
2,  382585541 bytes, 73.99 MB/s
3,  373035681 bytes, 68.46 MB/s
```
Highly compressible JSON (adresser.001, 1073741824 bytes):
```
1,  58161197 bytes, 288.94 MB/s
2,  48010017 bytes, 301.03 MB/s
3,  44563592 bytes, 357.03 MB/s
```
VM Image (rawstudio-mint14.tar, 8558382592 bytes):
```
1, 4030083076, 105.52 MB/s
2, 3956375446, 98.82 MB/s
3, 3924833672, 96.13 MB/s
```
> Rewrite level 2+3+4 compression

- flate/deflate.go
- flate/deflate_test.go
- flate/snappy.go
- flate/token.go
Rewrite level 1 to a new level 2, that can do cross-block matching.
Currently this is a rewrite of level 1 which allows us to retain the hash table between blocks. It is close to the same speed as level 1, but no previous block matching has been added.
* Implement level 2 (cross-block matches) and level 3 (2 checks per hash).
* Only check second candidate if value mismatches.
* Fine tune compression settings.
* Rebalance to adjust for new compression levels.
* For level 3, add another hash to the table before resuming.
* Adjustments to balance.
* Restore compressed content performance
* Fix flush/reset.
* Simplify offset handling for faster encoding.
* Also attempt to match first byte
* Initialize to maxStoreBlockSize to invalidate zero values.
* Add specialized level 4 which checks …
> Rewrite level 2+3+4 compression (#61)

- flate/snappy.go
- Allow full offset matches.
- Adjust input margin to actual limits.
- When match ends a block, index the following target item.
- Do longer back-matching after match on level 3+4.
> Fine tune level 2-4

- README.md
Hi! This pr fixes typo in readme.
> Correct package name in drop-in replacement table

- gzip/example_test.go
Even though this is still being debated in https://github.com/golang/go/issues/18085 we might as well change it.
> Fix "Println arg list ends with redundant newline"

- fse/bitreader.go
- fse/bytereader.go
- fse/compress.go
- fse/fse.go
- fse/fse_test.go
- fse/fuzz/run-compress.cmd
- fse/fuzz/run-decompress.cmd
It seems like Go SSA has code for combining two byte loads into a word load. Use that:
```
name                       old time/op    new time/op    delta
Decompress/gettysburg-8      7.48µs ± 3%    7.11µs ± 3%  -4.92%        (p=0.000 n=10+10)
Decompress/digits-8           331µs ± 2%     328µs ± 3%    ~            (p=0.156 n=9+10)
Decompress/twain-8           1.49ms ± 4%    1.50ms ± 5%    ~           (p=0.436 n=10+10)
Decompress/low-ent-8          130µs ± 3%     127µs ± 4%  -2.36%         (p=0.043 n=9+10)
Decompress/superlow-ent-8    32.8µs ± 3%    32.3µs ± 2%  -1.77%        (p=0.011 n=10+10)
Decompress/endzerobits-8      268ns ± 3%     269ns ± 2%    ~           (p=0.444 n=10+10)
Decompress/pngdata.001-8      147µs ± 2%     142µs ± 3%  -4.02%         (p=0.000 n=9+10) …
```
> Combine loads

- fse/bitwriter.go
- fse/compress.go
If tablelog is sufficiently small, encode 4 bytes between each flush.
Have a look at the reason for the small regression.
```
name                     old time/op    new time/op    delta
Compress/gettysburg-8      10.2µs ± 0%    10.5µs ± 1%   +3.17%          (p=0.008 n=5+5)
Compress/digits-8           498µs ± 1%     503µs ± 2%     ~             (p=0.151 n=5+5)
Compress/twain-8           2.12ms ± 0%    2.12ms ± 1%     ~             (p=0.730 n=4+5)
Compress/low-ent-8          215µs ± 3%     214µs ± 2%     ~             (p=1.000 n=5+5)
Compress/superlow-ent-8    58.0µs ± 2%    58.4µs ± 1%     ~             (p=0.310 n=5+5)
Compress/endzerobits-8      775ns ± 2%     642ns ± 3%  -17.13%          (p=0.008 n=5+5)
Compress/pngdata.001-8      281µs ± 1%     282µs ± 2%     ~             (p=1.000 …
```
> FSE: Encode 4 bytes between flushing

- zstd/encoder.go
- zstd/encoder_options.go
- zstd/encoder_test.go
- zstd/frameenc.go
WithEncoderPadding will add padding to all output so the size will be a multiple of n.
This can be used to obfuscate the exact output size.
The contents will be a skippable frame, so it will be invisible by the decoder.
The padded area will be filled with data from crypto/rand.Reader.
'n' must be > 0 and <= 1GB, 1<<30 bytes.
If `EncodeAll` is used with data already in the destination, the total size will be multiple of this.
> zstd: Add WithEncoderPadding

- zstd/decoder.go
- zstd/framedec.go
- zstd/zstd.go
Refuse decoding single segment frames if they exceed the promised size.
Also, if a bytes.Buffer is passed, check the size and do single threaded decoding if less than 1MB.
> zstd: Stricter size checks on single segments

- zstd/bitreader.go
- zstd/blockdec.go
- zstd/decoder_test.go
- zstd/framedec.go
- zstd/fse_decoder.go
- zstd/seqdec.go
Add test to help identify where mismatches occur by hashing big files and compare output.
Should eventually fix #124 
Actual block, match length mismatch (`43974` vs `43973`)
```
zstd_decompress.c: neededInSize = 3 
zstd_decompress.c: ZSTD_decompressContinue (srcSize:3) 
zstd_decompress.c: stage zdss_read 
zstd_decompress.c: neededInSize = 22 
zstd_decompress.c: ZSTD_decompressStream 
zstd_decompress.c: input size : 25 
zstd_decompress.c: stage zdss_read 
zstd_decompress.c: neededInSize = 22 
zstd_decompress.c: ZSTD_decompressContinue (srcSize:22) 
zstd_decompress.c: ZSTD_decompressContinue: case ZSTDds_decompressBlock 
zstd_decompress.c: ZSTD_decompressContinue: case bt_compressed 
zstd_decompress_block.c: ZSTD_decompressBlock_internal (size : 22) 
zstd_decompress_block.c: …
```
> Fix wrong decoder output

- zstd/README.md
- zstd/decoder.go
- zstd/framedec.go
```
benchmark                                            old ns/op     new ns/op     delta
BenchmarkDecoder_DecodeAll/kppkn.gtb.zst-12          608499        610005        +0.25%
BenchmarkDecoder_DecodeAll/geo.protodata.zst-12      136501        137699        +0.88%
BenchmarkDecoder_DecodeAll/plrabn12.txt.zst-12       1967989       1944000       -1.22%
BenchmarkDecoder_DecodeAll/lcet10.txt.zst-12         1448010       1444000       -0.28%
BenchmarkDecoder_DecodeAll/asyoulik.txt.zst-12       504333        504333        +0.00%
BenchmarkDecoder_DecodeAll/alice29.txt.zst-12        650494        652504        +0.31%
BenchmarkDecoder_DecodeAll/html_x_4.zst-12           267000        267199        +0.07%
BenchmarkDecoder_DecodeAll/paper-100k.pdf.zst-12     24840         24659         -0.73% …
```
> Remove the last decoder allocation

- huff0/decompress.go
Avoid bounds check when reading bits:
```
e:\gopath\src\github.com\klauspost\compress\huff0>benchstat old.txt new.txt
name                                     old time/op    new time/op    delta
Decompress4XNoTable/digits-12               245µs ± 1%     224µs ± 1%   -8.62%         (p=0.000 n=10+9)
Decompress4XNoTable/gettysburg-12          3.39µs ± 1%    3.16µs ± 1%   -7.03%        (p=0.000 n=10+10)
Decompress4XNoTable/twain-12                741µs ± 1%     674µs ± 1%   -9.12%         (p=0.000 n=9+10)
Decompress4XNoTable/low-ent.10k-12         75.4µs ± 1%    68.2µs ± 0%   -9.57%        (p=0.000 n=10+10)
Decompress4XNoTable/superlow-ent-10k-12    20.2µs ± 1%    18.8µs ± 1%   -7.21%        (p=0.000 n=10+10)
Decompress4XNoTable/case1-12                321ns ± 1%     322ns ± 1%     ~ …
```
> huff0: Faster 4x decompression

- zstd/enc_dfast.go
- zstd/enc_fast.go
The compiler can figure out that they are not needed.
5-10% speed increase.
> zstd enc: Remove unneeded masks

- huff0/compress_test.go
- zstd/blockenc.go
Use single stream literal encoding for small blocks.
Saves a few bytes per block and tiny bit faster.
> zstd: Use single stream literal encoding

- README.md
- zstd/encoder.go
- zstd/encoder_test.go
If we did not get a single match, assume that the data cannot be entropy compressed.
It is very likely that the data is random, and in the rare case it is not, we can live with it.
Before:
```
BenchmarkRandomEncodeAllFastest-12           100          10475190 ns/op        1001.01 MB/s           0 B/op          0 allocs/op
BenchmarkRandomEncodeAllDefault-12           100          11075653 ns/op         946.74 MB/s           0 B/op          0 allocs/op
BenchmarkRandomEncoderFastest-12             200           8126950 ns/op        1290.25 MB/s         139 B/op          2 allocs/op
BenchmarkRandomEncoderDefault-12             200           8059989 ns/op        1300.96 MB/s          90 B/op          2 allocs/op
```
After:
```
BenchmarkRandomEncodeAllFastest-12           300           4425967 …
```
> zstd: Skip random data faster

- zstd/encoder.go
- zstd/encoder_options.go
- zstd/encoder_test.go
- zstd/frameenc.go
Needed for https://github.com/Shopify/sarama/pull/1477
> Add full zero payload block encoding option.

- zstd/decoder.go
- zstd/encoder.go
- zstd/fse_predefined.go
- zstd/snappy.go
Requested by https://github.com/Shopify/sarama/pull/1477
> Lazy init of zstd tables.

- zstd/encoder.go
- zstd/encoder_options.go
- zstd/encoder_options_test.go
- zstd/encoder_test.go
- zstd/framedec.go
Enabling smaller window sizes will save memory when working exclusively with smaller payloads. In addition, in some cases it offers faster compression with very similar results. Large window sizes are supported but are probably inadvisable in most situations.
> add WithWindowSize for configurable window size

- zstd/decoder.go
- zstd/decoder_test.go
When using the io.Reader interface don't block for more data when we have something.
Fixes #168
> zstd: Allow partial reads

- zstd/encoder_test.go
- zstd/fse_encoder.go
When writing FSE tables, check if we have enough space.
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/215
> zstd: Check destination buffer size

- huff0/compress.go
- huff0/compress_test.go
- huff0/huff0.go
- zstd/blockenc.go
- zstd/enc_dfast.go
- zstd/zstd.go
zstd would reject huff0 compressed literals if the improvement was too small.
However, this would update the huff0 state to contain a new table which could be reused. In that case a wrong table could be used for the next block.
We move the rejection code to huff0, so the state can be properly maintained.
Fixes #170
> zstd: Fix reuse of huff0 when data hard to compress

- flate/huffman_bit_writer.go
Switch literalFreq, offsetFreq, codegen to use arrays.
No need for separate allocations.
> bit_writer: Use arrays.

- flate/inflate.go
Use uint16 for chunks. Not 100% sure this is safe, so testing a bit.
No measurable performance difference.
> inflate: Reduce memory use

- zstd/decoder_test.go
- zstd/framedec.go
Fix frame content size reading on very large blocks.
> zstd: Fix frame content size decoding

- flate/huffman_bit_writer.go
- flate/stateless.go
Remove stateless allocations with a sync.Pool.
Remove unneeded zeroing.
```
λ benchstat old.txt new.txt
name                  old time/op    new time/op    delta
EncodeDigitsSL1e4-12     128µs ± 1%     130µs ± 5%     ~     (p=0.690 n=5+5)
EncodeDigitsSL1e5-12     847µs ± 0%     853µs ± 1%   +0.71%  (p=0.016 n=5+5)
EncodeDigitsSL1e6-12    7.77ms ± 1%    7.76ms ± 1%     ~     (p=0.841 n=5+5)
EncodeTwainSL1e4-12      140µs ± 0%     139µs ± 2%     ~     (p=0.151 n=5+5)
EncodeTwainSL1e5-12      873µs ± 0%     865µs ± 0%   -0.94%  (p=0.008 n=5+5)
EncodeTwainSL1e6-12     7.95ms ± 0%    7.91ms ± 0%   -0.54%  (p=0.032 n=5+5)
name                  old speed      new speed      delta
EncodeDigitsSL1e4-12  78.2MB/s ± 1%  77.1MB/s ± 5%     ~     (p=0.690 n=5+5)
EncodeDigitsSL1e5-12   118MB/s ± 0% …
```
> Add pool for bitwriters

- s2/encode_other.go
- s2/s2_test.go
On single, extremely large single block encodes with high extremely long repeats, we could store the wrong length.
Does not affect streaming mode.
> S2: limit max repeat length

- zstd/blockenc.go
- zstd/encoder.go
- zstd/encoder_options.go
- zstd/snappy.go
WithNoEntropyCompression will always skip entropy compression of literals.
This can be useful if content has matches, but unlikely to benefit from entropy compression.
Usually the slight speed improvement is not worth enabling this.
> Add WithNoEntropyCompression to zstd

- README.md
- zstd/blockdec.go
- zstd/decoder_test.go
- zstd/encoder_test.go
- zstd/snappy_test.go
- zstd/zstd_test.go
Adds gorouine leak detection. Only tests themselves were leaking.
Fixes #189  (as much as possible)
> Clean up test decoders

- zstd/decoder.go
This is mostly for convenience.
> zstd: Add function to get decoder as io.ReadCloser

- zstd/README.md
(I don't know why does the last line show up in the diff :man_shrugging: )
> Fix typo ration => ratio in README.md

- zstd/encoder.go
Default single segment wasn't as intended. Tweak it to be enabled between Minimum Window and 1MB.
For small sizes it adds 1-2 bytes of overhead, so we only add it above minimum window.
> zstd: Tweak singlesegment default

- huff0/bitwriter.go
- huff0/compress.go
- zstd/blockenc.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/encoder.go
- zstd/encoder_test.go
With a one type data source:
```
λ benchstat old.txt new.txt
name                                 old time/op    new time/op    delta
Encoder_EncodeAllSimple4K/fastest-2    31.7µs ± 0%    27.1µs ± 0%  -14.46%        (p=0.000 n=10+10)
Encoder_EncodeAllSimple4K/default-2    49.0µs ± 0%    44.9µs ± 0%   -8.51%        (p=0.000 n=10+10)
name                                 old speed      new speed      delta
Encoder_EncodeAllSimple4K/fastest-2   129MB/s ± 0%   151MB/s ± 0%  +16.90%        (p=0.000 n=10+10)
Encoder_EncodeAllSimple4K/default-2  83.5MB/s ± 0%  91.3MB/s ± 0%   +9.30%        (p=0.000 n=10+10)
```
> Optimize single block encodes

- s2/cmd/internal/readahead/LICENSE
- s2/cmd/internal/readahead/README.md
- s2/cmd/internal/readahead/reader.go
- s2/cmd/s2c/main.go
- s2/cmd/s2d/main.go
Increases compression speed by almost 1GB/s on systems with plenty of CPU.
2548.8MB/s ->  3856.9MB/s
Decompression speedup is about 10%, if not IO limited:
1255.1MB/s ->  1386.8MB/s
> s2c+s2d: Add readahead

- README.md
- zip/reader.go
- zip/writer.go
- zip/writer_test.go
Allow copying content from an existing ZIP file without decompressing+compressing.
New API:
```Go
// Copy will copy raw content from input file.
// Optionally a different name can be given to the new file.
func (w *Writer) Copy(name string, src *File) error
// OpenRaw returns a Reader that returns the *compressed* output of the file.
func (f *File) OpenRaw() (io.Reader, error)
// CreateHeaderRaw adds a file to the zip archive using the provided FileHeader
// for the file metadata. Writer takes ownership of fh and may mutate
// its fields. The caller must not modify fh after calling CreateHeaderRaw.
//
// This returns a Writer to which the compressed file contents should be written.
// The file's contents must be written to the io.Writer before the next
// call to Create, Copy, …
```
> Add compressed ZIP copying

- flate/fast_encoder.go
- flate/level1.go
- flate/level2.go
- flate/level3.go
- flate/level4.go
- flate/level5.go
- flate/level6.go
- flate/writer_test.go
With many resets without encoding (much) data e.cur could overflow.
Fixes #217
> Fix reset overflow

- flate/deflate.go
- flate/deflate_test.go
Furthermore:
* Clean up dictionary handling & test.
* Fixes dictionary use in levels 1-6.
Fixes #219
> Remove writer reference on close

- zstd/blockenc.go
- zstd/bytebuf.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/encoder.go
- zstd/encoder_options_test.go
- zstd/framedec.go
- zstd/fse_decoder.go
- zstd/fse_encoder.go
- zstd/zstd.go
Fix reset overflow similar to #128
Change assertions to separate param.
Reduce max window size.
Fixes #225
> zstd: Fix reset overflow

- flate/deflate_test.go
- flate/huffman_bit_writer.go
- flate/huffman_code.go
- flate/inflate.go
When a block is not marked as the final block it should be possible to read 10 further bits ahead without breaking the promise of not overreading.
Fixes #231
Also write blocks with only EOF as TYPE 01 (predefined tables) with only an EOB literal. This saves 3-4 bytes at no cost.
The smallest block seems to be a predefined block with a single EOB, which would be 10 bits + EOB from current block (current limit).
This should make it possible to fill more bits at the time when decoding.
```
λ benchcmp old.txt new.txt
benchmark                       old ns/op     new ns/op     delta
BenchmarkGunzipCopy-12          27830317      26617762      -4.36%
BenchmarkGunzipNoWriteTo-12     27878505      26705660      -4.21%
benchmark                       old MB/s     new MB/s     speedup …
```
> inflate: Read more bits when decoding

- flate/inflate.go
```
λ benchcmp old.txt new.txt
benchmark                       old ns/op     new ns/op     delta
BenchmarkGunzipCopy-32          22523140      19900003      -11.65%
BenchmarkGunzipNoWriteTo-32     22542379      19977600      -11.38%
BenchmarkGunzipStdlib-32        23444056      23435431      -0.04%
benchmark                       old MB/s     new MB/s     speedup
BenchmarkGunzipCopy-32          211.91       239.85       1.13x
BenchmarkGunzipNoWriteTo-32     211.73       238.91       1.13x
BenchmarkGunzipStdlib-32        203.59       203.66       1.00x
```
> inflate: Inline symbol read

- zstd/encoder.go
Only EncodeAll uses the channel of encoders, so only allocate it when needed there.
Fixes #235
Reported by @jpchen-lightstep
> Skip creating encoders when not needed

- zstd/enc_better.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/encoder_options.go
- zstd/encoder_test.go
- zstd/zstd.go
Add compression mode that is better than default.
Approximately 50% of the throughput with ~5% overall improvement. Roughly the same as zstd level 7-8.
Some comparisons (best of 3 runs):
```
file	out	level	insize	outsize	millis	mb/s
enwik9	zskp	2	1000000000	317517832	7452	127.96
enwik9	zskp	3	1000000000	295162043	13341	71.48
nyc-taxi-data-10M.csv	zskp	2	3325605752	595200765	14299	221.80
nyc-taxi-data-10M.csv	zskp	3	3325605752	548223444	27764	114.23
github-june-2days-2019.json	zskp	2	6273951764	640407088	14517	412.15
github-june-2days-2019.json	zskp	3	6273951764	604145629	35487	168.60
rawstudio-mint14.tar	zskp	2	8558382592	3379874208	42571	191.72
rawstudio-mint14.tar	zskp	3	8558382592	3287441065	90137	90.55
silesia.tar	zskp	2	211947520	67542426	1254	161.15
silesia.tar	zskp	3	211947520 …
```
> zstd: Add better compression mode

- zstd/enc_fast.go
- zstd/zstd.go
Inline matchlen code and slightly simplify it. This loses a small amount of compression but gives a big speedup. This seems reasonable at the fastest level.
Before/after, best of 3 runs each:
```
file	out	level	insize	outsize	millis	mb/s
enwik9	zskp	1	1000000000	343831004	4202	226.91
enwik9	zskp	1	1000000000	343848582	3682	258.97
github-june-2days-2019.json	zskp	1	6273951764	698824137	10787	554.67
github-june-2days-2019.json	zskp	1	6273951764	699045015	10474	571.23
github-ranks-backup.bin	zskp	1	1862623243	454018274	4833	367.54
github-ranks-backup.bin	zskp	1	1862623243	454072815	4568	388.82
rawstudio-mint14.tar	zskp	1	8558382592	3667295557	21060	387.55
rawstudio-mint14.tar	zskp	1	8558382592	3667489370	20207	403.90
nyc-taxi-data-10M.csv	zskp	1	3325605752	641244049	10954	289.53 …
```
> zstd: Improve match speed of fastest level.

- s2/encode.go
- s2/encode_all.go
- s2/encode_amd64.go
- s2/encode_go.go
- s2/encodeblock_amd64.go
- s2/encodeblock_amd64.s
- s2/gen.go
Don't fall back to original snappy.
> s2: Add pure Go snappy block compressor

- flate/deflate.go
- flate/inflate.go
- fse/fse.go
- gzip/gzip.go
- huff0/huff0.go
- s2/encode.go
- zstd/blockdec.go
- zstd/enc_better.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/enc_params.go
- zstd/encoder_options.go
- zstd/framedec.go
Align elements in structs to avoid padding.
> all: Smaller struct sizes

- zstd/encoder.go
If if writing header (ie first block) and it is the final block, use block compression instead of async.
Addition for #248
> zstd: If first block and 'final', encode direct.

- zstd/blockdec.go
- zstd/decoder_test.go
- zstd/framedec.go
Size of small decodes reduced by more than an order of magnitude by allocating less pessimisticly.
> zstd: Reduce per decoder allocations significantly

- zstd/blockdec.go
Raw blocks don't need a destination since it is always forwarded directly.
The panic should be unreachable. Adding it for sanity check since it is harmless.
> Reduce raw block allocs

- zstd/seqdec.go
```
benchmark                                               old ns/op      new ns/op      delta
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-32          4704626        4312341        -8.34%
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-32      1068883        984396         -7.90%
BenchmarkDecoder_DecoderSmall/plrabn12.txt.zst-32       18021576       15813727       -12.25%
BenchmarkDecoder_DecoderSmall/lcet10.txt.zst-32         13398648       11872693       -11.39%
BenchmarkDecoder_DecoderSmall/asyoulik.txt.zst-32       3892600        3691969        -5.15%
BenchmarkDecoder_DecoderSmall/alice29.txt.zst-32        5005336        4613696        -7.82%
BenchmarkDecoder_DecoderSmall/html_x_4.zst-32           2099041        2012320        -4.13% …
```
> zstd: Inline nextFast call

- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/encoder.go
Increment buffer offset when encoding without history.
Since it does not store history, we must offset `e.cur` to avoid false matches for next user.
Fixes the need for double resets to clear history.
Only allocate history when we need to encode more than 1 block.
Replaces #262
> zstd: Increment buffer offset

- zip/writer.go
This adds the zip64 field handling identical to [fileWriter.Close](https://github.com/klauspost/compress/blob/26bacdfece2923f6b0b4c7abb1a9527628c73c89/zip/writer.go#L612).
Without this, it is far easier to create an invalid ZIP file. This provides convenience for when you only want to set the compressed data length and CRC32 fields after using `zip.FileInfoHeader`, rather than handle multiple fields manually.
> zip: update CreateHeaderRaw to handle zip64 fields.

- zstd/blockenc.go
- zstd/encoder.go
- zstd/encoder_options.go
- zstd/encoder_test.go
- zstd/snappy.go
Skip entropy compression on random data in fastest mode.
Can be tweaked via an option if so desired.
Random data ~2x faster in fastest mode.
> zstd: Skip entropy on random data

- huff0/bitwriter.go
- huff0/compress.go
- huff0/compress_test.go
- huff0/decompress.go
- huff0/huff0.go
Populate the "previous" compression when reading table.
Add mode that forces reuse of previous table and never generates a new.
Allow bare table to be used.
> huff0: Populate compression table

- zstd/blockenc.go
- zstd/encoder.go
- zstd/encoder_test.go
Two 'last' blocks was added on small payloads when using ReadFrom.
Fixes #277
> zstd: Fix ReadFrom with small blocks

- flate/fast_encoder.go
- flate/gen_inflate.go
- flate/huffman_bit_writer.go
- flate/inflate.go
- flate/inflate_gen.go
- flate/regmask_amd64.go
- flate/regmask_other.go
Use and operations to speed up variable shifts.
Faster on AMD64:
```
benchmark                               old ns/op     new ns/op     delta
BenchmarkDecodeDigitsSpeed1e4-32        57027         56892         -0.24%
BenchmarkDecodeDigitsSpeed1e5-32        657866        650408        -1.13%
BenchmarkDecodeDigitsSpeed1e6-32        6679774       6425893       -3.80%
BenchmarkDecodeDigitsDefault1e4-32      62810         61858         -1.52%
BenchmarkDecodeDigitsDefault1e5-32      657865        628677        -4.44%
BenchmarkDecodeDigitsDefault1e6-32      6486343       6211232       -4.24%
BenchmarkDecodeDigitsCompress1e4-32     62169         61555         -0.99%
BenchmarkDecodeDigitsCompress1e5-32     677789        668714        -1.34%
BenchmarkDecodeDigitsCompress1e6-32     6851431 …
```
> inflate: Limit variable shifts

- zstd/encoder.go
- zstd/encoder_test.go
Flush any pending writes when ReadFrom is used.
This fixes the race with the Write content as well.
> zstd: Fix mixed Write and ReadFrom calls

- zstd/decoder.go
Default to compressed size * 2 if no frame size and no destination buffer given.
> zstd: Tweak DecodeAll standard allocs

- s2/_generate/gen.go
- s2/encodeblock_amd64.go
- s2/encodeblock_amd64.s
Remove code that handles cases where we are beyond possible block limits.
> s2: Simplify small blocks with known max size.

- zstd/blockenc.go
Currently the literal encoder can be carried over.
Not currently needed, but could give unexpected results in the future.
> zstd: Always reset literal dict encoder

- zstd/README.md
- zstd/enc_best.go
- zstd/encoder_options.go
- zstd/encoder_test.go
Add slow compression mode, but with the best compression ratio available
Allows a nice size improvement over "better" mode, but at a significant CPU penalty.
Typical speed is currently around 25MB/s
Some speed examples:
```
file		 		comp	level	insize	outsize	millis	mb/s
github-june-2days-2019.json	zskp	1	6273951764	699045015	11634	514.29
github-june-2days-2019.json	zskp	2	6273951764	617881763	17756	336.96
github-june-2days-2019.json	zskp	3	6273951764	537511906	35785	167.20
github-june-2days-2019.json	zskp	4	6273951764	512796117	103513	57.80
silesia.tar	zskp	1	211947520	73118028	713	283.09
silesia.tar	zskp	2	211947520	67504318	1049	192.50
silesia.tar	zskp	3	211947520	65102964	2466	81.93
silesia.tar	zskp	4	211947520	61381950	8115	24.91
enwik8	zskp	1	100000000	39176328	408	233.17
enwik8	zskp …
```
> zstd: Add Best compression mode

- zstd/decoder.go
- zstd/decoder_test.go
- zstd/zstd.go
> zstd: free Decoder resources when Reset is called with a nil io.Reader

- zstd/seqdec.go
Under some large streaming volume conditions (kafka consumption) this allocation can create tremendous GC pressure, where setting GOGC <= 10 still is not enough.  Since this condition does not happen "very often" (but seems to happen more often in this streaming case then originally advertised by the original comment) we only allocate as much as we need not an extra 2Mb slab.
Conditions:
- 2000 zstd encoded blocks second over 64 different streams byte blocks were in 1Mb chunks
Before this change:
- with in several seconds Ram consumption would jump from 200Mb to over 30Gb
- pprof indicated this allocation as the issue, however only ~500Mb inuse indicating GC had not cleaned up the other allocs
- turning on GOGC=5, stemmed the speed of OOM, but still eventually OOMed
After this change:
- …
> keep allocations as small as possible

- s2/README.md
- s2/cmd/s2c/main.go
- s2/encode.go
- s2/encode_best.go
- s2/encode_test.go
- s2/s2_test.go
Add compression mode that will compress the data very well, but at a significant performance decrease.
Mainly for offline compression, but where decompression speed should still be high and compatible with other S2 compressed data.
Comparing on 16 core CPU:
```
* enwik10:
Default... 10000000000 -> 4761467548 [47.61%]; 1.098s, 8685.6MB/s
Better... 10000000000 -> 4225922984 [42.26%]; 2.817s, 3385.4MB/s
Best... 10000000000 -> 3667646858 [36.68%]; 35.995s, 264.9MB/s
* github-june-2days-2019.json:
Default... 6273951764 -> 1043196283 [16.63%]; 431ms, 13882.3MB/s
Better... 6273951764 -> 950079555 [15.14%]; 736ms, 8129.5MB/s
Best... 6273951764 -> 846260870 [13.49%]; 8.125s, 736.4MB/s
* nyc-taxi-data-10M.csv:
Default... 3325605752 -> 1095998837 [32.96%]; 324ms, 9788.7MB/s
Better... 3325605752 -> …
```
> s2: Add 'best' compression option

- s2/decode.go
- s2/decode_test.go
- s2/encode.go
- s2/encode_test.go
ReaderMaxBlockSize allows to control allocations if the stream
has been compressed with a smaller WriterBlockSize, or with the default 1MB.
Blocks must be this size or smaller to decompress,
otherwise the decoder will return ErrUnsupported.
Fixes incorrect validation of WriterBlockSize parameter.
Changes NewReader to take options as varargs.
> s2: Add ReaderMaxBlockSize

- s2/cmd/s2d/main.go
- s2/decode.go
- s2/decode_other.go
- s2/s2_test.go
Removes and impossible check from the Go decoder, otherwise no changes.
> s2: Clean up decoder

- zip/writer.go
See also https://github.com/golang/go/issues/33116
The offset must be written into the central directory
as 0xFFFFFFFF if it's going to be written in the zip64
extended information field.
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
The following is the layout of the zip64 extended
information "extra" block. If one of the size or
offset fields in the Local or Central directory
record is too small to hold the required data,
a Zip64 extended information record is created.
The order of the fields in the zip64 extended
information record is fixed, but the fields MUST
only appear if the corresponding Local or Central
directory record field is set to 0xFFFF or 0xFFFFFFFF.
> fixes zip64 headers

- zstd/enc_best.go
- zstd/enc_fast.go
- zstd/encoder_test.go
Increase speed of incompressible data for "best"/"fastest" mode.
Should not have any impact on compressible data:
before/after...
```
sharnd.out.2gb	zskp	4	2147483647	2147581961	52931	38.69
sharnd.out.2gb	zskp	4	2147483647	2147581961	15426	132.76
silesia.tar	zskp	4	211947520	61381950	8394	24.08
silesia.tar	zskp	4	211947520	61327981	8142	24.82
BenchmarkRandom10MBEncodeAllFastest-32    	     279	   3971326 ns/op	2640.37 MB/s	       0 B/op	       0 allocs/op
BenchmarkRandom10MBEncodeAllFastest-32    	     349	   3498572 ns/op	2997.15 MB/s	       0 B/op	       0 allocs/op
```
> zstd: Increase speed on incompressible data for best

- s2/decode.go
- s2/decode_test.go
Allocate enough for the default window size and add
`ReaderAllocBlock` for custom allocs.
> s2: Smaller initial decoder alloc

- README.md
- s2/README.md
- s2/_generate/gen.go
- s2/cmd/s2c/main.go
- s2/encode_amd64.go
- s2/encode_better.go
- s2/encode_go.go
- s2/encodeblock_amd64.go
- s2/encodeblock_amd64.s
- s2/s2_test.go
Blocks:
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkTwainEncode1e1/better-32      10.7          10.5          -1.87%
BenchmarkTwainEncode1e2/better-32      2947          280           -90.50%
BenchmarkTwainEncode1e3/better-32      6664          2525          -62.11%
BenchmarkTwainEncode1e4/better-32      47401         25461         -46.29%
BenchmarkTwainEncode1e5/better-32      528060        417367        -20.96%
BenchmarkTwainEncode1e6/better-32      2137499       1554364       -27.28%
benchmark                                                  old ns/op     new ns/op     delta
BenchmarkRandomEncodeBetterBlock1MB-32                     39476         38241         -3.13%
BenchmarkEncodeS2Block/0-html/block-better-32              10140         6761 …
```
> s2: Add AMD64 assembly for better mode

- .travis.yml
- s2/decode_amd64.s
- s2/decode_arm64.s
- s2/decode_asm.go
- s2/decode_other.go
Adapted from Snappy equiv. Minor optimizations along the way.
```
enwik9 (stream):
Decompressing. 426854614 -> 1000000000 [234.27%]; 7.618s, 125.2MB/s
Decompressing. 426854614 -> 1000000000 [234.27%]; 4.258s, 224.0MB/s
Blocks:
benchmark                     old ns/op     new ns/op     delta
BenchmarkTwainDecode1e1-4     69.5          63.0          -9.27%
BenchmarkTwainDecode1e2-4     184           153           -16.61%
BenchmarkTwainDecode1e3-4     852           522           -38.74%
BenchmarkTwainDecode1e4-4     30220         14678         -51.43%
BenchmarkTwainDecode1e5-4     570195        231880        -59.33%
BenchmarkTwainDecode1e6-4     3349753       1920724       -42.66%
benchmark                     old MB/s     new MB/s     speedup
BenchmarkTwainDecode1e1-4     143.97       158.69 …
```
> s2: Add arm64 decompression

- s2/decode_other.go
Add another decode loop that doesn't check sizes as long as src is big enough.
For now only in Go version.
Streams:
```
Before: Decompressing. 426243297 -> 1000000000 [234.61%]; 1.941s, 491.3MB/s
After:  Decompressing. 426243297 -> 1000000000 [234.61%]; 1.895s, 503.3MB/s
```
Some blocks like it a lot:
```
BenchmarkDecodeS2Block/4-pdf/block-32                      379           336           -11.35%
BenchmarkDecodeS2Block/4-pdf/block-better-32               691           630           -8.83%
BenchmarkDecodeS2Block/4-pdf/block-best-32                 816           702           -13.97%
BenchmarkDecodeS2Block/5-html4/block-32                    13645         8727          -36.04%
BenchmarkDecodeS2Block/5-html4/block-better-32             14059         9204          -34.53% …
```
> s2: Avoid Decode size checks

- .travis.yml
- s2/cmd/_s2sx/_unpack/main.go
```
s2sx Self Extracting Archive
Usage: sample.tar.s2sfx.exe [options] [output-file/dir]
Use - as file name to extract to stdout when not untarring.
Options:
-force-untar
Always untar file
-help
Display help
-q    Don't write any output to terminal, except errors
-untar
Untar tar files if specified at creation (default true)
```
> s2sx: Add more extraction options

- flate/fast_encoder.go
- flate/level2.go
- fse/compress.go
- fse/decompress.go
- huff0/compress.go
- s2/s2.go
- snappy/snappy.go
- zip/reader.go
- zip/reader_test.go
- zip/zip_test.go
- zstd/encoder_test.go
- zstd/fse_encoder.go
- zstd/snappy.go
This PR gets rid of a bunch of unneeded type conversions. I was checking out the code and
saw a few of these myself, but most of them were fixed using [unconvert](https://github.com/mdempsky/unconvert).
> Fix a few unnecessary type conversions

- zstd/dict_test.go
- zstd/enc_base.go
- zstd/enc_better.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/encoder_options.go
All credit goes to @tony2001
As shown in #344 the speed of small dictionary compression tasks (< 32K) can be improved significantly by keeping track of the state of the hash table.
This effectively implements #344 but avoids a penalty for non-dictionary encodes and extends the functionality to the "better" compression mode as well.
This change will also make it easier to [remove the copy of the literal dictionary](https://github.com/klauspost/compress/blob/a0dc84a8cf242dde7e21f8aba26126ca4621ff8c/zstd/enc_base.go#L171) every time an encode starts and have specialized code to deal with this.
```
benchmark                                                                     old ns/op     new ns/op     delta
BenchmarkEncodeAllDict0_1024/length-19-level-fastest-dict-1-32                5729 …
```
> zstd: Big speedup on small dictionary encodes

- flate/deflate.go
- flate/deflate_test.go
- flate/flate_test.go
- flate/inflate_test.go
- flate/writer_test.go
- fse/compress.go
- gzip/gunzip_test.go
- gzip/gzip_test.go
- huff0/compress.go
- huff0/compress_test.go
- s2/cmd/internal/readahead/reader.go
- s2/cmd/s2c/main.go
- s2/s2_test.go
- zip/writer_test.go
- zstd/blockenc.go
- zstd/decodeheader.go
- zstd/decodeheader_test.go
- zstd/decoder.go
- zstd/decoder_options.go
- zstd/decoder_test.go
- zstd/encoder.go
- zstd/encoder_test.go
- zstd/framedec.go
- zstd/fse_encoder.go
- zstd/fse_predefined.go
- zstd/seqenc.go
This just fixes a few minor issues reported by staticcheck. Nothing major.
I did not know how to solve these, but I expect that they may be of interest for performance reasons:
```
/home/jacob/Git/compress/s2/encode.go
(402, 19)  SA6002  argument should be pointer-like to avoid allocations
(655, 18)  SA6002  argument should be pointer-like to avoid allocations
(734, 17)  SA6002  argument should be pointer-like to avoid allocations
(819, 17)  SA6002  argument should be pointer-like to avoid allocations
```
> Fix some minor issues reported by staticcheck

- zstd/enc_base.go
- zstd/zstd.go
Use less memory when encoding with dictionaries.
Bonus: Simplify loading.
> zstd: Allocate less when encoding

- s2/README.md
- s2/cmd/s2c/main.go
- s2/cmd/s2d/main.go
> s2: Make allow commandline input to be http/https

- s2/_generate/gen.go
- s2/encodeblock_amd64.s
Keep BP in an XMM register while running.
> See discussion on Slack and `golang-dev`
> 
> https://gophers.slack.com/archives/C6WDZJ70S/p1598210629000900
> https://groups.google.com/g/golang-dev/c/aLn9t8tKg2o/m/Kw-N7lUuBAAJ
> 
> Summary:
> 
> * `BP` should be callee-save (poorly documented, even some standard library assembly didn't handle this correctly until recently)
> * `BP` "will be saved automatically if there is a nonzero frame size" https://golang.org/cl/248260
> 
> * Use the "nonzero frame size" hack in the case where `BP` has been used
> Save BP register to XMM

- s2/cmd/_s2sx/_unpack/main.go
- s2/cmd/_s2sx/go.sum
- s2/cmd/_s2sx/main.go
- s2/cmd/s2c/main.go
Also make sure to truncate output files.
> s2sx: Add stdin input

- .travis.yml
- s2/encode_best.go
Improves compression.
Use more accurate scoring function for best mode. More often a benefit than not.
```
BEFORE/AFTER:
Reading nyc-taxi-data-10M.csv...
Compressing... 3325605752 -> 794873465 [23.90%]; 6.172s, 513.9MB/s
Compressing... 3325605752 -> 786648492 [23.65%]; 7.389s, 429.2MB/s
Reading adresser.json...
Compressing... 7983034785 -> 375370404 [4.70%]; 3.527s, 2158.6MB/s
Compressing... 7983034785 -> 380912248 [4.77%]; 3.924s, 1940.0MB/s
Reading 10gb.tar...
Compressing... 10065157632 -> 5246634524 [52.13%]; 24.294s, 395.1MB/s
Compressing... 10065157632 -> 5215462149 [51.82%]; 29.462s, 325.8MB/s
Reading enwik9...
Compressing... 1000000000 -> 375981068 [37.60%]; 3.562s, 267.7MB/s
Compressing... 1000000000 -> 373289535 [37.33%]; 4.047s, 235.6MB/s
Reading sample.tar...
Compressing... …
```
> s2: More accurate scoring in best mode

- s2/_generate/gen.go
- s2/encode_better.go
- s2/encodeblock_amd64.s
Index more entries at beginning and end of matches.
Before/after:
```
Reading d:\compress\enwik9...
Compressing... 1000000000 -> 426242923 [42.62%]; 225ms, 4244.2MB/s
Compressing... 1000000000 -> 418428483 [41.84%]; 230ms, 4154.8MB/s
Reading d:\compress\adresser.json...
Compressing... 7983034785 -> 457984083 [5.74%]; 507ms, 15018.9MB/s
Compressing... 7983034785 -> 453666648 [5.68%]; 494ms, 15424.7MB/s
Reading d:\compress\nyc-taxi-data-10M.csv...
Compressing... 3325605752 -> 935022950 [28.12%]; 462ms, 6870.2MB/s
Compressing... 3325605752 -> 917905514 [27.60%]; 460ms, 6889.8MB/s
```
> s2: Improve better compression

- zstd/README.md
- zstd/enc_best.go
See if we can find a better match by checking where the current best ends.
Use that offset to see if we can find a better full match.
Before/after. Ignore speed, may not be comparable:
```
gob-stream  zskp    4   1911399616  171537212   32113   56.76
gob-stream  zskp    4   1911399616  167273881   29337   62.13
enwik9  zskp    4   1000000000  276609671   44029   21.66
enwik9  zskp    4   1000000000  275241169   36430   26.18
github-june-2days-2019.json zskp    4   6273951764  512796117   97791   61.18
github-june-2days-2019.json zskp    4   6273951764  503314661   93811   63.78
nyc-taxi-data-10M.csv   zskp    4   3325605752  495986829   89368   35.49
nyc-taxi-data-10M.csv   zskp    4   3325605752  490907191   65939   48.10
```
> zstd: Improve best compression

- zstd/zip.go
- zstd/zip_test.go
Adds ZipCompressor and ZipDecompressor as well as method constants.
Winzip confirmed... PKWARE, no idea... download form doesn't work.
7zip detects it, but cannot decompress.
> zstd: Add helpers to compress/decompress zstd inside zip files

- zstd/enc_better.go
Try to find a better match by searching for a long match
at the end of the current best match
Before/after pairs.. Speed comparison not reliable, different Go versions.
```
silesia.tar zskp    3   211947520   65177448    1899    106.44
silesia.tar zskp    3   211947520   64595893    2007    100.68
gob-stream  zskp    3   1911399616  185792019   9324    195.48
gob-stream  zskp    3   1911399616  175034659   9636    189.17
enwik9  zskp    3   1000000000  294540704   11725   81.34
enwik9  zskp    3   1000000000  292243069   12162   78.41
github-june-2days-2019.json zskp    3   6273951764  537511906   29252   204.54
github-june-2days-2019.json zskp    3   6273951764  524340691   34043   175.75
rawstudio-mint14.tar    zskp    3   8558382592  3224594213  71751   113.75
rawstudio-mint14.tar …
```
> zstd: Improve better compression

- flate/level5.go
- flate/level6.go
Improve deflate level 5+6 compression by checking an additional hash when the best found match ends.
This improves compression in most cases at an acceptable speed loss which brings it will in line with the surrounding parameters.
Level 5 tries one hash at length < 30 and level 6 tries 2 at all lengths.
Before/after pairs...
```
file	out	level	insize	outsize	millis	mb/s
github-june-2days-2019.json	gzkp	5	6273951764	963122453	31498	189.96
github-june-2days-2019.json	gzkp	5	6273951764	947567306	32795	182.45
github-june-2days-2019.json	gzkp	6	6273951764	949824639	34851	171.68
github-june-2days-2019.json	gzkp	6	6273951764	930428507	37312	160.35
nyc-taxi-data-10M.csv	gzkp	5	3325605752	785784479	24729	128.25
nyc-taxi-data-10M.csv	gzkp	5	3325605752	779343831	27189	116.65
nyc-taxi-data-10M.csv …
```
> deflate: Improve level 5+6 compression

- s2/README.md
- s2/cmd/_s2sx/_unpack/main.go
- s2/cmd/_s2sx/main.go
Work around problem with operating system limits and make executable a max size.
Continue to another file.
Change output file name to use `s2sx`
> s2sx: Limit max executable size

- zstd/zip.go
> Mark ZipMethodPKWare as deprecated

- README.md
- flate/fast_encoder.go
- flate/huffman_code.go
- flate/reader_test.go
Reduce history from 640KB to 320KB.
Allocate freqcache in the encoder.
> flate: Allocate less for history.

- zstd/decoder_test.go
- zstd/framedec.go
Detect short frame signatures, sizes 1 ->3 bytes.
Fixes #381
> zstd: Detect short invalid signatures

- s2/encode.go
- s2/encode_test.go
EncodeBuffer cannot safely reuse the buffer in concurrent usage.
> s2: Clarify EncodeBuffer usage

- gzhttp/README.md
- gzhttp/gzip.go
- gzhttp/gzip_test.go
Fixes https://github.com/nytimes/gziphandler/issues/87
> gzhttp: Support Flush always

- zstd/blockdec.go
- zstd/decoder_options.go
- zstd/decoder_test.go
- zstd/framedec.go
Also reduce default memory allocs.
Fixes #390
Replaces #392
> zstd: Add configurable Decoder window size

- s2/_generate/gen.go
- s2/encodeblock_amd64.go
- s2/encodeblock_amd64.s
Use bigger output margin and utilize it to reduce memmove branching.
Before -> after (best of 10)
```
Compressing... 10737418240 -> 4455442050 [41.49%]; 2.964s, 3454.9MB/s
Compressing... 10737418240 -> 4455442050 [41.49%]; 2.805s, 3650.2MB/s
Compressing... 10737418240 -> 4562648848 [42.49%]; 860ms, 11907.1MB/s
Compressing... 10737418240 -> 4562648848 [42.49%]; 856ms, 11960.0MB/s
Compressing... 10065157632 -> 5540789702 [55.05%]; 1.55s, 6193.7MB/s
Compressing... 10065157632 -> 5540789702 [55.05%]; 1.53s, 6273.7MB/s
Compressing... 10065157632 -> 5916578242 [58.78%]; 983ms, 9765.1MB/s
Compressing... 10065157632 -> 5916578242 [58.78%]; 972ms, 9878.3MB/s
Compressing... 10000000000 -> 4129259395 [41.29%]; 1.967s, 4848.0MB/s
Compressing... 10000000000 -> 4129259395 [41.29%]; 1.857s, 5134.7MB/s …
```
> s2: Improve speed with bigger output margin

- s2/README.md
- s2/_generate/gen.go
- s2/cmd/s2c/main.go
- s2/cmd/s2d/main.go
- s2/encode.go
- s2/encode_all.go
- s2/encode_amd64.go
- s2/encode_best.go
- s2/encode_better.go
- s2/encode_go.go
- s2/encode_test.go
- s2/encodeblock_amd64.go
- s2/encodeblock_amd64.s
- s2/s2.go
- s2/s2_test.go
S2 can now fully replace snappy and generate snappy output at all compression levels, including streaming.
Comparison of [`webdevdata.org-2015-01-07-subset`](https://files.klauspost.com/compress/webdevdata.org-2015-01-07-4GB-subset.7z),
53927 files, total input size: 4,014,735,833 bytes. amd64, single goroutine used:
| Encoder               | Size       | MB/s   |
|-----------------------|------------|--------|
| snappy.Encode         | 1128706759 | 725.59 |
| s2.EncodeSnappy       | 1093823291 | 899.16 |
| s2.EncodeSnappyBetter | 1001158548 | 578.49 |
| s2.EncodeSnappyBest   | 944507998  | 66.00  |
Comparison of different streams, AMD Ryzen 3950x, 16 cores. Size and throughput: 
| File                        | snappy.NewWriter         | S2 Snappy                 | S2 Snappy, Better …
> s2: Add full Snappy output support

- s2/cmd/_s2sx/main.go
Fixes `ERROR: max size less than unpacker. Max size must be at least 2170369 bytes`.
Use `s2sx -max=1024MB` as a workaround.
> s2sx: Fix max size error

- zstd/dict_test.go
- zstd/enc_base.go
- zstd/encoder.go
- zstd/encoder_test.go
Add `ResetContentSize` which will allow to set the frame content size of an incoming stream.
This can be used to help the decoder if it is known.
> zstd: Add stream content size

- zstd/enc_best.go
- zstd/enc_better.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/hash.go
Inlining now works properly with constant folding.
> zstd: Simplify hashing functions

- gzhttp/gzip.go
`http.HandlerFunc` is more flexible and offers the `http.Handler` interface.
Very lightly breaking change.
> gzhttp: Return http.HandlerFunc instead of http.Handler

- zstd/decoder.go
- zstd/decoder_test.go
Fix error forwarding when writing the final block.
Fixes #408
> zstd: Fix WriteTo error forwarding

- gzhttp/gzip_test.go
This makes the test work in IPv6-only environments, too.
> tests: listen on “localhost” instead of IPv4

- zstd/zip.go
This code was previously Get'ing objects from one pool and later Put'ing them to a different pool, so they were never reused.
> zstd: pooledZipWriter should return Writers to the same pool

- flate/fast_encoder.go
> flate: Remove unneeded bounds checks (effectively one less)

- flate/huffman_bit_writer.go
Huffman only:
320.36 -> 414.67MB/s  (github-june-2days-2019.json)
237.41-> 293.24 MB/s (github-ranks-backup.bin)
Level 1:
278.94 -> 308.47 MB/s  (github-june-2days-2019.json)
232.93 -> 261.16MB/s  (github-ranks-backup.bin)
> deflate: Speed up huffman encoding

- compressible_test.go
- flate/deflate.go
- flate/writer_test.go
- gzip/gzip_test.go
> deflate: Improve cost estimate, level 7-9

- zstd/internal/xxhash/xxhash_arm64.s
- zstd/internal/xxhash/xxhash_asm.go
- zstd/internal/xxhash/xxhash_other.go
see https://github.com/cespare/xxhash/pull/51
```
benchmark                                                    old ns/op      new ns/op      delta
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-16               14740529       14093294       -4.39%
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-16           3003737        3008035        +0.14%
BenchmarkDecoder_DecoderSmall/plrabn12.txt.zst-16            70052218       70885931       +1.19%
BenchmarkDecoder_DecoderSmall/lcet10.txt.zst-16              33424884       34714144       +3.86%
BenchmarkDecoder_DecoderSmall/asyoulik.txt.zst-16            9694846        9563735        -1.35%
BenchmarkDecoder_DecoderSmall/alice29.txt.zst-16             12322865       12782681       +3.73%
BenchmarkDecoder_DecoderSmall/html_x_4.zst-16 …
```
> zstd: add arm64 xxhash assembly

- zstd/bitreader.go
- zstd/fse_decoder.go
- zstd/seqdec.go
Around 1%. Parallel results are outliers.
```
benchmark                                                    old ns/op     new ns/op     delta
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-32               4569931       4482917       -1.90%
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-32           1041234       1035972       -0.51%
BenchmarkDecoder_DecoderSmall/plrabn12.txt.zst-32            14863278      14590060      -1.84%
BenchmarkDecoder_DecoderSmall/lcet10.txt.zst-32              10867406      10873836      +0.06%
BenchmarkDecoder_DecoderSmall/asyoulik.txt.zst-32            3639723       3623579       -0.44%
BenchmarkDecoder_DecoderSmall/alice29.txt.zst-32             4795746       4712242       -1.74%
BenchmarkDecoder_DecoderSmall/html_x_4.zst-32                1998022       2011177 …
```
> zstd: Minor decoder improvements

- huff0/decompress.go
Improve for tablelog > 8:
```
benchmark                                           old ns/op     new ns/op     delta
BenchmarkDecompress4XNoTable/gettysburg-32          2760          2711          -1.78%
BenchmarkDecompress4XNoTable/twain-32               583900        580407        -0.60%
BenchmarkDecompress4XNoTable/pngdata.001-32         79094         77148         -2.46%
BenchmarkDecompress4XNoTableTableLog8/digits-32     158182        158284        +0.06%
BenchmarkDecompress4XTable/digits-32                160960        158540        -1.50%
BenchmarkDecompress4XTable/gettysburg-32            3985          3907          -1.96%
BenchmarkDecompress4XTable/twain-32                 585743        585507        -0.04%
BenchmarkDecompress4XTable/low-ent.10k-32           55110         55175 …
```
> huff0: Improve 4X decompression speed

- s2/README.md
- s2/cmd/internal/readahead/reader.go
- s2/cmd/s2c/main.go
- s2/cmd/s2d/main.go
- s2/decode.go
- s2/encode.go
- s2/encode_test.go
- s2/index.go
- s2/index_test.go
- s2/s2.go
S2 and Snappy streams can have indexes. These indexes will allow random seeking within the compressed data.
The index can either be appended to the stream as a skippable block or returned for separate storage.
When the index is appended to a stream it will be skipped by regular decoders, 
so the output remains compatible with other decoders. 
To automatically add an index to a stream, add `WriterAddIndex()` option to your writer.
Then the index will be added to the stream when `Close()` is called.
```
// Add Index to stream...
enc := s2.NewWriter(w, s2.WriterAddIndex())
io.Copy(enc, r)
enc.Close()
```
If you want to store the index separately, you can use `CloseIndex()` instead of the regular `Close()`.
This will return the index. Note that `CloseIndex()` should only be called once, and …
> s2: Add stream index

- zstd/encoder_options.go
Keep 64K blocks for fastest, but do max size for others.
Healthy compression increase for streams.
(ignore speed)
```
BEFORE:
github-june-2days-2019.json	zskp	1	6273951764	698989536	12717	470.49
github-june-2days-2019.json	zskp	2	6273951764	617881763	18084	330.86
github-june-2days-2019.json	zskp	3	6273951764	524340691	37059	161.45
github-june-2days-2019.json	zskp	4	6273951764	468052601	170093	35.18
AFTER:
github-june-2days-2019.json	zskp	1	6273951764	698768123	10316	580.00
github-june-2days-2019.json	zskp	2	6273951764	610876538	13942	429.13
github-june-2days-2019.json	zskp	3	6273951764	517662858	42937	139.35
github-june-2days-2019.json	zskp	4	6273951764	464617114	165806	36.09
BEFORE:
github-ranks-backup.bin	zskp	1	1862623243	454073018	4646	382.27
github-ranks-backup.bin	zskp	2	1862623243 …
```
> zstd: Add bigger default blocks

- flate/deflate.go
- flate/huffman_bit_writer.go
- flate/huffman_code.go
- flate/token.go
```
github-june-2days-2019.json 899480979 -> 897825289
nyc-taxi-data-10M.csv 709158534 ->  710347717
enwik9 324078757 ->  321763532
github-ranks-backup.bin 435530626 -> 435990909
gob-stream 279987188 -> 278123843
silesia.tar 68817867 -> 68271872
```
> flate: Improve level 7-9 (again)

- flate/deflate.go
Keep expensive check for level 9.
> flate: Increase level 7+8 speed and compression

- flate/level3.go
Fix most cases where level 3 is worse than level 2, by inserting intermediate hashes on skipped sections and increase level 3 table size.
Also fixes immediate matches not being caught.
> flate: Improve level 3 compression

- flate/fast_encoder.go
- flate/huffman_bit_writer.go
- flate/level1.go
- flate/token.go
Mainly through manual inlining.
```
BenchmarkEncodeDigitsSpeed1e4-32     53121         47995         -9.65%
BenchmarkEncodeDigitsSpeed1e5-32     686799        630834        -8.15%
BenchmarkEncodeDigitsSpeed1e6-32     6636421       6054570       -8.77%
BenchmarkEncodeTwainSpeed1e4-32      77016         69146         -10.22%
BenchmarkEncodeTwainSpeed1e5-32      690640        634364        -8.15%
BenchmarkEncodeTwainSpeed1e6-32      6915519       6367504       -7.92%
BenchmarkEncodeDigitsSpeed1e4-32     188.25       208.35       1.11x
BenchmarkEncodeDigitsSpeed1e5-32     145.60       158.52       1.09x
BenchmarkEncodeDigitsSpeed1e6-32     150.68       165.16       1.10x
BenchmarkEncodeTwainSpeed1e4-32      129.84       144.62       1.11x
BenchmarkEncodeTwainSpeed1e5-32      144.79 …
```
> flate: Improve level 1 speed by ~10%

- flate/huffman_bit_writer.go
- flate/huffman_code.go
- flate/token.go
```
λ benchcmp before.txt after.txt
benchmark                            old ns/op     new ns/op     delta
BenchmarkEncodeDigitsSpeed1e4-32     48523         47923         -1.24%
BenchmarkEncodeDigitsSpeed1e5-32     642126        632069        -1.57%
BenchmarkEncodeDigitsSpeed1e6-32     6197352       6046440       -2.44%
BenchmarkEncodeTwainSpeed1e4-32      70716         69414         -1.84%
BenchmarkEncodeTwainSpeed1e5-32      641631        632854        -1.37%
BenchmarkEncodeTwainSpeed1e6-32      6432128       6323973       -1.68%
benchmark                            old MB/s     new MB/s     speedup
BenchmarkEncodeDigitsSpeed1e4-32     206.09       208.67       1.01x
BenchmarkEncodeDigitsSpeed1e5-32     155.73       158.21       1.02x
BenchmarkEncodeDigitsSpeed1e6-32     161.36 …
```
> flate: Faster token writer, 1-2% on fastest

- flate/huffman_code.go
Mainly gains for small blocks & fastest levels.
```
benchmark                               old ns/op     new ns/op     delta
BenchmarkEncodeDigitsConstant1e4-32     16080         15984         -0.60%
BenchmarkEncodeDigitsSpeed1e4-32        48105         45890         -4.60%
BenchmarkEncodeDigitsDefault1e4-32      114016        111234        -2.44%
BenchmarkEncodeDigitsCompress1e4-32     228570        225041        -1.54%
BenchmarkEncodeDigitsSL1e4-32           46695         45006         -3.62%
BenchmarkEncodeTwainConstant1e4-32      23557         22033         -6.47%
BenchmarkEncodeTwainSpeed1e4-32         68594         63177         -7.90%
BenchmarkEncodeTwainDefault1e4-32       112498        111798        -0.62%
BenchmarkEncodeTwainCompress1e4-32      282909        274804 …
```
> flate: Improve huffman generation speed ~5% faster

- flate/huffman_bit_writer.go
- zstd/enc_fast.go
Improve speed for zstd fastest and huffman-only compression of random data.
flate: 590.71MB/s -> 1512.99MB/s
zstd l1: 1840.07MB/s -> 2489.23MB/s
> Improve incompressible data speed

- huff0/decompress.go
- zstd/decoder_test.go
Skip zeroing stack and add a bigger reusable buffer:
```
benchmark                                            old ns/op     new ns/op     delta
BenchmarkDecompress4XNoTable/digits-32               200409        151974        -24.17%
BenchmarkDecompress4XNoTable/gettysburg-32           2610          2565          -1.72%
BenchmarkDecompress4XNoTable/twain-32                558870        532480        -4.72%
BenchmarkDecompress4XNoTable/low-ent.10k-32          57291         53948         -5.84%
BenchmarkDecompress4XNoTable/superlow-ent-10k-32     15556         14443         -7.15%
BenchmarkDecompress4XNoTable/case1-32                296           257           -13.28%
BenchmarkDecompress4XNoTable/case2-32                250           206           -17.27% …
```
> huff0: Use static decompression buffer up to 30% faster

- huff0/decompress.go
- huff0/huff0.go
Also make buffers safe from concurrent decoder use.
```
benchmark                                            old ns/op     new ns/op     delta
BenchmarkDecompress1XTable/digits-32                 256367        262489        +2.39%
BenchmarkDecompress1XTable/gettysburg-32             5189          5224          +0.67%
BenchmarkDecompress1XTable/twain-32                  825950        825534        -0.05%
BenchmarkDecompress1XTable/low-ent.10k-32            88050         88429         +0.43%
BenchmarkDecompress1XTable/superlow-ent-10k-32       23420         23456         +0.15%
BenchmarkDecompress1XTable/crash2-32                 687           676           -1.59%
BenchmarkDecompress1XTable/endzerobits-32            80.9          78.4          -3.07%
BenchmarkDecompress1XTable/endnonzero-32 …
```
> huff0: Use buffers for 1X decodes

- zip/writer.go
[fastzip](https://github.com/saracen/fastzip) had reports of malformed compressed data (https://github.com/saracen/fastzip/issues/32). I've narrowed the fix down to this.
I'll update `fastzip` to call the non-deprecated function now, but fixing this here is still a good idea. [gitLab-runner ](https://gitlab.com/gitlab-org/gitlab-runner) uses fastzip and stumbled across this issue when the `klauspost/compress` dependency was indirectly updated via a minor minio upgrade. 😢
> Update deprecated CreateHeaderRaw to correctly call CreateRaw

- zstd/decoder.go
- zstd/encoder.go
- zstd/encoder_options.go
- zstd/encoder_test.go
Do not use goroutines when encoder concurrency is 1.
Fixes #264
Can probably be cleaned up a bit.
> zstd: Add stream encoding without goroutines

- flate/deflate_test.go
- flate/level1.go
- flate/level2.go
- flate/level3.go
- flate/level4.go
- flate/level5.go
- flate/level6.go
- flate/stateless.go
- flate/token.go
~2% faster.
Emit long matches as length 255, since it saves bits.
> flate: Inline literal emission

- zstd/blockdec.go
- zstd/decoder_test.go
- zstd/seqdec.go
Copy appears better than append. In async streaming where we know the size, use copy instead of append.
Simplify some checks.
```
STREAM BEFORE: (best of 5)
BenchmarkDecoderEnwik9-32              4     275810800 ns/op     362.57 MB/s       53570 B/op         44 allocs/op
BenchmarkDecoderSilesia-32             3     389839700 ns/op     543.68 MB/s     2148208 B/op         44 allocs/op
BenchmarkDecoderJSON-32             1    6487052600 ns/op     967.15 MB/s      101128 B/op         68 allocs/op
STREAM AFTER: (best of 5)
BenchmarkDecoderEnwik9-32              4     252812900 ns/op     395.55 MB/s       53970 B/op         45 allocs/op
BenchmarkDecoderSilesia-32             3     360591267 ns/op     587.78 MB/s     2148309 B/op         45 allocs/op
BenchmarkDecoderJSON-32            1 …
```
> zstd: Improve decompression speed

- huff0/decompress_amd64.s
- huff0/decompress_amd64.s.in
When not filling there is no reason to check if exhausted.
```
BenchmarkDecompress4XNoTable/gettysburg/10000-32            11867         11550         -2.67%
BenchmarkDecompress4XNoTable/gettysburg/262143-32           336139        331035        -1.52%
BenchmarkDecompress4XNoTable/twain/10000-32                 11922         11561         -3.03%
BenchmarkDecompress4XNoTable/twain/262143-32                387406        374386        -3.36%
BenchmarkDecompress4XNoTable/pngdata.001/10000-32           12262         11961         -2.45%
BenchmarkDecompress4XNoTable/pngdata.001/262143-32          319131        308746        -3.25%
```
> huff0: Skip unneeded exhaust check

- huff0/decompress_8b_amd64.s
- huff0/decompress_amd64.s
- huff0/decompress_amd64.s.in
Go v1.18 feature. Set `GOAMD64=v3` to enable. Nothing worth having separate codepaths for.
Allows breaking dependency chain a bit.
```
benchmark                                              old ns/op     new ns/op     delta
BenchmarkDecompress4XNoTable/gettysburg/10000-32       11464         11195         -2.35%
BenchmarkDecompress4XNoTable/gettysburg/262143-32      322679        319985        -0.83%
BenchmarkDecompress4XNoTable/twain/10000-32            11505         11238         -2.32%
BenchmarkDecompress4XNoTable/twain/262143-32           373751        370410        -0.89%
BenchmarkDecompress4XNoTable/pngdata.001/10000-32      11957         11461         -4.15%
BenchmarkDecompress4XNoTable/pngdata.001/262143-32     306403        300566        -1.91%
```
> huff0: Use bmi1 on GOAMD64=v3

- zstd/seqdec_test.go
I wrote these unit tests to validate an assembler version of the code. The procedure is non-trivial and I guess it might be handy to have tests for it. I know that the procedure is inlined in some places, but anyway.
> tests: [zstd] Unit tests for sequenceDecs.adjustOffset

- internal/cpuinfo/cpuinfo.go
- internal/cpuinfo/cpuinfo_amd64.go
- internal/cpuinfo/cpuinfo_amd64.s
For now, we need to know whether an x86 CPU supports the BMI extensions.
I made it a separate module, as it may be used not only in `zstd`.
I tested the code manually, but TBH I don't know how to unit test this.
> cpuinfo: get x86 features in runtime

- internal/cpuinfo/cpuinfo.go
- zstd/_generate/gen.go
- zstd/seqdec_amd64.go
- zstd/seqdec_amd64.s
- zstd/seqdec_amd64_test.go
- zstd/seqdec_test.go
* Add non-bmi amd64 tests
* Use BEXTRQ for extracting shifted values.
* Move 0 check into getBits.
* Remove ctx alloc.
Sequences only, BMI:
```
benchmark                                                                                          old ns/op     new ns/op     delta
Benchmark_seqdec_decode/n-12286-lits-13914-prev-9869-1990358-3296656-win-4194304.blk-32            91657         91114         -0.59%
Benchmark_seqdec_decode/n-12485-lits-6960-prev-976039-2250252-2463561-win-4194304.blk-32           92392         90416         -2.14%
Benchmark_seqdec_decode/n-14746-lits-14461-prev-209-8-1379909-win-4194304.blk-32                   83022         79745         -3.95%
Benchmark_seqdec_decode/n-1525-lits-1498-prev-2009476-797934-2994405-win-4194304.blk-32            9149          8856 …
```
> zstd: Asm decoder tweaks

- zstd/_generate/gen.go
- zstd/decoder_test.go
- zstd/seqdec.go
- zstd/seqdec_amd64.go
- zstd/seqdec_amd64.s
- zstd/seqdec_generic.go
This is plain x86 and x86 with BMI2 implementation of `sequenceDecs.executeSimple`. Part of #515.
I extracted function `executeSimple` to handle cases when no history nor dictionary is used. My quick check showed that for `go test` such cases is 83% of all calls, while for `go test -bench .` it's 99%. Thus, it's the vast majority of cases. Of course, we may consider handling all cases in another PR (but after completing #529).
~As always, I'm marking it as a draft, as some tests fail. I will figure out what's wrong, likely as usual I missed something silly.~ [fixed (I was right, it was silly)]
Below are preliminary benchmark results from IceLake machine: it's noasm vs GOARM64=v3. Currently, the branch is built on top of #528, thus we see the combined performance boost from x86 BMI use in …
> zstd: x86 assembler implementation of sequenceDecs.executeSimple

- zstd/zip.go
Decompressor would return error when finishing.
Add options to `ZipDecompressor`.
> zstd: Fix decompressor, add options

- zstd/_generate/gen.go
- zstd/seqdec.go
- zstd/seqdec_amd64.go
- zstd/seqdec_amd64.s
- zstd/seqdec_generic.go
Add history support in the asm implementation. Part of task #515.
~As usual marking as a draft, because of few failing tests.~ [fixed]
Performance comparison between the current master and this branch on an IceLake machine with the hacked `decodeSync` is below. There are some nice speedups, but there are also regressions for almost all cases without history. To overcome that, we can have two specialisations: `executeWithoutDictionary` and `executeWithoutDictionatyAndHistory` - what do you think?
```
benchmark                                                                 old ns/op     new ns/op     delta
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-16                            3819656       3185382       -16.61%
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-16 …
```
> zstd: extend executeSimple with history support

- huff0/decompress_amd64.go
Before/After:
```
BenchmarkDecoderEnwik9-32    	       1	1439142300 ns/op	 694.86 MB/s	 1536592 B/op	    7681 allocs/op
BenchmarkDecoderEnwik9-32    	       1	1382877200 ns/op	 723.13 MB/s	   71856 B/op	      50 allocs/op
```
> huff0: Fix noescape pragma

- zstd/blockdec.go
- zstd/seqdec_amd64.go
Before/after:
```
BenchmarkDecoderSilesia-32    	       4	 281834900 ns/op	 752.03 MB/s	 1623058 B/op	      44 allocs/op
BenchmarkDecoderSilesia-32    	       4	 251419725 ns/op	 843.00 MB/s	   50090 B/op	      43 allocs/op
BenchmarkDecoderEnwik9-32    	       1	1460882800 ns/op	 684.52 MB/s	   71856 B/op	      50 allocs/op
BenchmarkDecoderEnwik9-32    	       1	1439168800 ns/op	 694.85 MB/s	   71440 B/op	      49 allocs/op
```
> zstd: Over-alloc destination by 16 bytes

- zstd/_generate/gen.go
- zstd/seqdec_amd64.s
Not super visible in microbenches (presumably because of cache), but very visible in streaming decodes.
Before/after:
```
BenchmarkDecoderSilesia-32    	       4	 281168525 ns/op	 753.81 MB/s	   50218 B/op	      44 allocs/op
BenchmarkDecoderSilesia-32    	       6	 190584583 ns/op	1112.09 MB/s	   49446 B/op	      45 allocs/op
BenchmarkDecoderEnwik9-32    	       1	1439964200 ns/op	 694.46 MB/s	   71952 B/op	      51 allocs/op
BenchmarkDecoderEnwik9-32    	       1	1184307200 ns/op	 844.38 MB/s	   72144 B/op	      53 allocs/op
```
> zstd: Store previous offsets in registers

- zstd/_generate/gen.go
- zstd/decoder_test.go
- zstd/seqdec.go
- zstd/seqdec_amd64.s
Remove redundant `CMPQ`. Fix error reporting on decodeSync.
Fixes #549
> zstd: Fix offset check when ll == 0

- s2/encode_test.go
- s2/index.go
```
cpu: AMD Ryzen 9 3950X 16-Core Processor
BenchmarkIndexFind
BenchmarkIndexFind/blocks-1-32         	194769370	         6.180 ns/op	       0 B/op	       0 allocs/op
BenchmarkIndexFind/blocks-2-32         	199258790	         6.057 ns/op	       0 B/op	       0 allocs/op
BenchmarkIndexFind/blocks-4-32         	204297220	         5.879 ns/op	       0 B/op	       0 allocs/op
BenchmarkIndexFind/blocks-8-32         	190476280	         6.321 ns/op	       0 B/op	       0 allocs/op
BenchmarkIndexFind/blocks-16-32        	158611744	         7.537 ns/op	       0 B/op	       0 allocs/op
BenchmarkIndexFind/blocks-32-32        	100000000	        10.04 ns/op	       0 B/op	       0 allocs/op
BenchmarkIndexFind/blocks-64-32        	79986668	        14.90 ns/op	       0 B/op	       0 allocs/op …
```
> s2: Use sorted search for index

- zstd/_generate/gen.go
- zstd/decoder_test.go
- zstd/seqdec.go
- zstd/seqdec_amd64.go
- zstd/seqdec_amd64.s
- zstd/seqdec_generic.go
A little hacking in the current generator allowed us to reuse almost all code. That's nice!
Part of #515.
For now `go test -run TestDecoder` pass, I'm working on fixing the remaining tests. Another thing is that PR does not incorporate yet the history support (waiting for #542)
Benchmark results from an Ice Lake machine. Some quite good speed ups are there!
```
benchmark                                                                 old ns/op     new ns/op     delta
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-16                            4948849       3115659       -37.04%
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-16                        884190        525662        -40.55%
BenchmarkDecoder_DecoderSmall/plrabn12.txt.zst-16                         16820567      13477758 …
```
> zstd: asm version of decodeSync

- zstd/decodeheader_test.go
- zstd/decoder_test.go
- zstd/dict_test.go
Some repeated code got removed.
> zstd: use helper function to create a zip reader in tests

- zstd/decoder_test.go
It's for users who want to benchmark against their own files.
An expected invocation is: `go test -run XYZ -bench BenchmarkDecoderWithCustomFiles`
> zstd: Add benchmark for custom files

- zstd/decoder.go
- zstd/decoder_options.go
- zstd/decoder_test.go
- zstd/framedec.go
Closes #571 
There might be scenarios for which checksum validation is not necessary.
> zstd: Allow to ignore checksum checking

- flate/_gen/gen_inflate.go
- flate/inflate_gen.go
```
λ benchcmp before.txt  after.txt
benchmark                               old ns/op     new ns/op     delta
BenchmarkDecodeDigitsSpeed1e4-32        45478         44642         -1.84%
BenchmarkDecodeDigitsSpeed1e5-32        520045        506007        -2.70%
BenchmarkDecodeDigitsSpeed1e6-32        5213200       5067185       -2.80%
BenchmarkDecodeDigitsDefault1e4-32      49476         48936         -1.09%
BenchmarkDecodeDigitsDefault1e5-32      496733        490872        -1.18%
BenchmarkDecodeDigitsDefault1e6-32      4869294       4851319       -0.37%
BenchmarkDecodeDigitsCompress1e4-32     44262         44419         +0.35%
BenchmarkDecodeDigitsCompress1e5-32     470795        473693        +0.62%
BenchmarkDecodeDigitsCompress1e6-32     4690131       4689175       -0.02% …
```
> inflate: Keep dict on stack

- zstd/_generate/gen.go
- zstd/decoder_test.go
- zstd/seqdec_amd64.s
Use faster method for `copyMemory` and `copyOverlappedMemory`.
```
λ benchcmp before.txt after.txt
benchmark                                                    old ns/op     new ns/op     delta
BenchmarkDecoder_DecodeAllParallel/kppkn.gtb.zst-32          17933         14089         -21.44%
BenchmarkDecoder_DecodeAllParallel/geo.protodata.zst-32      4489          3847          -14.30%
BenchmarkDecoder_DecodeAllParallel/plrabn12.txt.zst-32       56959         44537         -21.81%
BenchmarkDecoder_DecodeAllParallel/lcet10.txt.zst-32         44430         33115         -25.47%
BenchmarkDecoder_DecodeAllParallel/asyoulik.txt.zst-32       15040         12049         -19.89%
BenchmarkDecoder_DecodeAllParallel/alice29.txt.zst-32        18360         14098         -23.21% …
```
> zstd: Faster decoding memcopy in asm

- zstd/decoder_test.go
> zstd: Add IgnoreChecksum test to basic decoder UTs

- huff0/decompress.go
This is only really needed when compressing anyway.
(affects reading zstd dictionaries)
Fixes #585
> huff0: Do not check max size when reading table.

- zstd/decoder.go
Use the main reader goroutine to decompress literals.
Never an actual bottleneck, so we may as well reduce the synchronization.
No speed impact.
> zstd: Use 1 less goroutine for stream decoding

- zstd/_generate/gen.go
- zstd/blockdec.go
- zstd/decoder_test.go
- zstd/seqdec_amd64.go
- zstd/seqdec_amd64.s
- zstd/seqdec_test.go
Also reduces literal overalloc when full allocs are allowed.
```
benchmark                                                                                          old ns/op     new ns/op     delta
BenchmarkDecoder_DecodeAllParallel/kppkn.gtb.zst-32                                                14572         13898         -4.63%
BenchmarkDecoder_DecodeAllParallel/geo.protodata.zst-32                                            3946          3682          -6.69%
BenchmarkDecoder_DecodeAllParallel/plrabn12.txt.zst-32                                             45150         43296         -4.11%
BenchmarkDecoder_DecodeAllParallel/lcet10.txt.zst-32                                               33525         36679         +9.41%
BenchmarkDecoder_DecodeAllParallel/asyoulik.txt.zst-32 …
```
> zstd: Copy literal in 16 byte blocks when possible

- zstd/_generate/gen.go
- zstd/seqdec.go
- zstd/seqdec_amd64.s
Use the Go-code approach: use single getBits to obtain three bitfields.
Results from an Ice Lake machine. Not big improvement, but still something.
```
benchmark                                                                 old ns/op     new ns/op     delta
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-16                            3538269       3464588       -2.08%
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-16                        767535        762036        -0.72%
BenchmarkDecoder_DecoderSmall/plrabn12.txt.zst-16                         12020124      11753140      -2.22%
BenchmarkDecoder_DecoderSmall/lcet10.txt.zst-16                           9370142       9150443       -2.34%
BenchmarkDecoder_DecoderSmall/asyoulik.txt.zst-16                         2888949       2847418 …
```
> zstd: faster next state update in BMI2 version of decode

- flate/deflate.go
- flate/fast_encoder.go
Remove stateful hash and need for AND operation.
Benchmarks show no change.
Fixes #589
> flate: Inplace hashing for level 7-9

- huff0/bitreader.go
- huff0/bitwriter.go
- huff0/bytereader.go
- huff0/compress.go
- huff0/decompress.go
Another batch of `staticcheck` findings.
> huff0: remove unused function and types

- zstd/decoder_test.go
- zstd/framedec.go
Typically an improvement when limited by the execute stage (enwik9)
```
BenchmarkDecoderEnwik9/multithreaded-writer-32         	       1	1184100400 ns/op	 844.52 MB/s	13992400 B/op	     101 allocs/op
BenchmarkDecoderEnwik9/multithreaded-writer-himem-32   	       1	1095716200 ns/op	 912.65 MB/s	19551184 B/op	      63 allocs/op
BenchmarkDecoderEnwik9/singlethreaded-writer-32        	       1	1612467600 ns/op	 620.17 MB/s	 6602968 B/op	      29 allocs/op
BenchmarkDecoderEnwik9/singlethreaded-writerto-32      	       1	1631256700 ns/op	 613.02 MB/s	 6590776 B/op	      26 allocs/op
BenchmarkDecoderEnwik9/singlethreaded-himem-32         	       1	1338224000 ns/op	 747.26 MB/s	 8835640 B/op	      23 allocs/
BenchmarkDecoderSilesia/multithreaded-writer-32         	       5	 201332380 ns/op …
```
> zstd: Speed up when WithDecoderLowmem(false)

- s2/_generate/gen.go
- s2/encodeblock_amd64.s
When emitting the final literals we may not have enough input to safely read all without over-reading.
Set output margin to 0 for exact copies in this case.
Fixes #600
> s2: amd64 - Fix final emit oob read crash

- zstd/enc_better.go
- zstd/enc_dfast.go
Will improve compression ever so slightly.
Bonus: Load table values in same order they are used.
> zstd: Fix incorrect hash table placement for dict encoding in default

- zstd/zip.go
This was only applied when options were specified.
> zstd: Apply default config to ZipDecompressor without options

- s2/encode_best.go
Saves a byte here and there, nothing significant.
> snappy: Use dedicated function for scoring

- .github/workflows/go.yml
- .github/workflows/release.yml
Trying to eliminate
```
• checking config:
• DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check https://goreleaser.com/deprecations/#builds-for-windowsarm64 for more info.
• DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
• DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check https://goreleaser.com/deprecations/#builds-for-windowsarm64 for more info.
• DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
• DEPRECATED: skipped windows/arm64 build on Go < 1.17 for compatibility, check …
```
> tests: Bump goreleaser version

- flate/huffman_bit_writer.go
- flate/huffman_code.go
Faster histogram for hufman only compression; 1% overall speedup.
```
github-ranks-backup.bin	gzkp	-2	1862623243	1298789681	5528	321.30
github-ranks-backup.bin	gzkp	-2	1862623243	1298789681	5471	324.63
```
> flate: Faster histograms

- flate/huffman_bit_writer.go
- flate/huffman_code.go
~5% Faster for huffman-only, same for rest.
Before/after:
```
github-ranks-backup.bin	gzkp	-2	1862623243	1298789681	5547	320.22
github-ranks-backup.bin	gzkp	-2	1862623243	1298789681	5305	334.83
```
Replaces #619 - more speedup, and no regression.
> deflate: Use compound hcode

- .github/workflows/go.yml
- .github/workflows/release.yml
v0.7.0 requires Go 1.18. Upgrade & pin the dependency for now.
> tests: Pin garble version

- s2/decode.go
- s2/index_test.go
Un-indexed forward seeks does not preserve correct absolute offset when fully skipping blocks.
If stream is seekable, but no index is provided, allow non-random seeking.
Fixes #632
> s2: Fix absolute forward seeks

- zstd/_generate/gen.go
- zstd/seqdec_amd64.s
copyMemoryPrecise now generates a loop over 16-byte blocks with a single branchless 16-byte fixup after it. This is a tiny bit faster on the whole and quite a bit faster for some inputs.
<details><summary>Benchmark results on Intel Core i7-3770K</summary><pre>
name                                                         old speed      new speed      delta
Decoder_DecoderSmall/kppkn.gtb.zst-8                          369MB/s ± 0%   374MB/s ± 1%  +1.56%  (p=0.008 n=5+5)
Decoder_DecoderSmall/geo.protodata.zst-8                      977MB/s ± 0%  1056MB/s ± 1%  +8.17%  (p=0.008 n=5+5)
Decoder_DecoderSmall/plrabn12.txt.zst-8                       291MB/s ± 0%   289MB/s ± 0%  -0.74%  (p=0.008 n=5+5)
Decoder_DecoderSmall/lcet10.txt.zst-8                         329MB/s ± 1%   333MB/s ± 0% …
> zstd: Optimize seqdeq amd64 asm

- zstd/_generate/gen.go
- zstd/seqdec_amd64.s
Up to 25% faster decodes, depending on contents.
Use s2 memcopier and eliminate a zero check.
```
benchmark                                                                                       old MB/s     new MB/s     speedup
Benchmark_seqdec_execute/n-12286-lits-13914-prev-9869-1990358-3296656-win-4194304.blk-32        1284.77      1493.64      1.16x
Benchmark_seqdec_execute/n-12485-lits-6960-prev-976039-2250252-2463561-win-4194304.blk-32       1107.87      1580.86      1.43x
Benchmark_seqdec_execute/n-14746-lits-14461-prev-209-8-1379909-win-4194304.blk-32               3947.25      4163.99      1.05x
Benchmark_seqdec_execute/n-1525-lits-1498-prev-2009476-797934-2994405-win-4194304.blk-32        10281.12     10375.47     1.01x …
```
> zstd: Improve decoder memcopy

- huff0/_generate/gen.go
- huff0/decompress_amd64.go
- huff0/decompress_amd64.s
This makes the context object smaller and frees up three registers, which we can use to replace the limitPtr and bufferOrigin stack
variables.
Benchmark results show a tiny win (Go 1.19beta, Core i7-3770K):
name                                           old speed      new speed      delta
Decompress1XTable/digits-8                      347MB/s ± 0%   347MB/s ± 0%    ~     (p=0.650 n=8+10)
Decompress1XTable/gettysburg-8                  268MB/s ± 0%   268MB/s ± 0%    ~     (p=0.400 n=9+9)
Decompress1XTable/twain-8                       327MB/s ± 0%   327MB/s ± 1%    ~     (p=0.339 n=7+9)
Decompress1XTable/low-ent.10k-8                 385MB/s ± 0%   385MB/s ± 1%    ~     (p=0.510 n=9+10)
Decompress1XTable/superlow-ent-10k-8            376MB/s ± 0%   376MB/s ± 0%    ~     (p=0.712 n=8+10) …
> huff0: Pass a single bitReader pointer to asm

- s2/index.go
- s2/index_test.go
Add `RemoveIndexHeaders` that will remove 20 header+trailer bytes for cases when storage can be relied upon.
`RestoreIndexHeaders` will restore the index header+trailer so it can be loaded.
> s2: Add Index header trim/restore

- zstd/_generate/gen.go
- zstd/seqdec_amd64.s
This produces the same number of instructions, while requiring less generating code. Benchmarks on the Intel Core i7-3770K show a tiny speedup:
```
name                                                        old speed      new speed      delta
Decoder_DecoderSmall/kppkn.gtb.zst-8                         430MB/s ± 1%   437MB/s ± 1%  +1.60%  (p=0.000 n=10+9)
Decoder_DecoderSmall/geo.protodata.zst-8                    1.11GB/s ± 1%  1.13GB/s ± 0%  +1.37%  (p=0.000 n=9+9)
Decoder_DecoderSmall/plrabn12.txt.zst-8                      334MB/s ± 1%   339MB/s ± 1%  +1.41%  (p=0.000 n=9+10)
Decoder_DecoderSmall/lcet10.txt.zst-8                        392MB/s ± 2%   404MB/s ± 1%  +3.05%  (p=0.000 n=10+10)
Decoder_DecoderSmall/asyoulik.txt.zst-8                      355MB/s ± 2%   357MB/s ± 1%    ~ …
```
> zstd: Branchless getBits for amd64 w/o BMI2

- gzip/gunzip.go
Replace recursion with iteration in `Reader.Read` to avoid stack
exhaustion when there are a large number of files.
Fixes CVE-2022-30631
Upstream: https://github.com/golang/go/issues/53168
> gzip: fix stack exhaustion bug in Reader.Read

- zstd/decoder.go
- zstd/encoder.go
- zstd/encoder_options.go
- zstd/framedec.go
Also set single-segment when less than allowed window size.
> zstd: Allow single segments up to "max decoded size"

- zstd/seqdec_amd64.go
Using longer memory copies leads to rare, random crashes with fuzz testing.
It is therefore disabled for now.
> zstd: Disable extended memory copies (amd64)

- s2/decode_other.go
Only seems to help very small encodes really:
```
benchmark                                                                 old ns/op     new ns/op     delta
BenchmarkTwainDecode1e1/default-32                                        24.5          12.6          -48.61%
BenchmarkTwainDecode1e1/better-32                                         25.2          12.6          -49.90%
BenchmarkTwainDecode1e1/best-32                                           25.8          12.6          -51.14%
BenchmarkTwainDecode1e1/snappy-input-32                                   25.1          12.6          -49.66%
BenchmarkTwainDecode1e2/default-32                                        51.9          42.3          -18.41%
BenchmarkTwainDecode1e2/better-32                                         75.1 …
```
> s2: Slightly faster non-assembly decompression

- zstd/decoder.go
- zstd/decoder_options.go
- zstd/decoder_test.go
- zstd/framedec.go
WithDecodeAllCapLimit will limit DecodeAll to decoding cap(dst)-len(dst) bytes, or any size set in WithDecoderMaxMemory.
This can be used to limit decoding to a specific maximum output size.
Disabled by default.
Fixes #647
> zstd: Add DecodeAllCapLimit

- flate/level5.go
- flate/level6.go
Skip 2 bytes when doing end-of-match search.
This allows better matches to be picked up further forward, adding up to 2 literals, but giving a better match.
Level 5:
nyc: 779171549 -> 767765165
github-june: 943488021 -> 938777887
github-ranks: 435111686 -> 435008334
sofia: 3083510553 -> 3048677443
level6, nyc: 768119006 -> 753545897
Performance unchanged.
> flate: Improve level 5+6 compression

- zstd/enc_better.go
Skip 3 bytes when doing end-of-match search.
nyc: 529329260 -> 517666647 bytes
This allows better matches to be picked up further forward, adding up to 3 literals, but giving a better match.
Performance unchanged.
> zstd: Improve "better" compresssion

- s2/encode_best.go
Allow skipping bytes in the beginning. Since we already have pretty good matches we aren't too likely to find better.
Improvement in the 0.0x%->0.10% range.
> s2: Improve "best" compression

- flate/deflate.go
- flate/fast_encoder.go
- flate/huffman_bit_writer.go
- huff0/decompress.go
- huff0/decompress_generic.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
Requires Go 1.17
Replaces #424
> Use arrays for constant size copies

- zstd/fse_decoder_amd64.go
Regression from #598 causing excessive heap allocations.
> zstd: Fix non-effective noescape tag

- zstd/decoder.go
- zstd/decoder_options.go
- zstd/decoder_test.go
- zstd/framedec.go
- zstd/history.go
- zstd/seqdec.go
- zstd/seqdec_amd64.go
- zstd/seqdec_generic.go
Adds `WithDecodeBuffersBelow` to tweak buffer switch-over.
Fixes #666 and generally reduces Reader allocations.
> Fix+reduce allocations

- zstd/decoder_test.go
Output:
```
goos: windows
goarch: amd64
pkg: github.com/klauspost/compress/zstd
cpu: AMD Ryzen 9 3950X 16-Core Processor
BenchmarkDecoder_DecoderReset/kppkn.gtb.zst/stream-32  	    7342	    139579 ns/op	   0.01 MB/s	   93922 B/op	      16 allocs/op
BenchmarkDecoder_DecoderReset/kppkn.gtb.zst/stream-single-32         	29215276	        38.96 ns/op	  25.67 MB/s	       0 B/op	       0 allocs/op
BenchmarkDecoder_DecoderReset/kppkn.gtb.zst/buffer-32                	    4060	    280503 ns/op	   0.00 MB/s	       2 B/op	       0 allocs/op
BenchmarkDecoder_DecoderReset/kppkn.gtb.zst/buffer-single-32         	    4202	    280597 ns/op	   0.00 MB/s	       2 B/op	       0 allocs/op
BenchmarkDecoder_DecoderReset/geo.protodata.zst/stream-32            	   20731	     57093 ns/op	   0.02 MB/s	   61110 …
```
> tests: Add zstd Reset and NewReader benchmarks.

- zstd/enc_best.go
```
benchstat -delta-test none old2.txt new2.txt
name                                  old time/op    new time/op     delta
Encoder_EncodeAllXML-16                 13.3ms ± 0%     13.0ms ± 0%    -2.11%
Encoder_EncodeAllSimple/fastest-16       229µs ± 0%      227µs ± 0%    -1.08%
Encoder_EncodeAllSimple/default-16       343µs ± 0%      371µs ± 0%    +8.13%
Encoder_EncodeAllSimple/better-16        402µs ± 0%      393µs ± 0%    -2.33%
Encoder_EncodeAllSimple/best-16         6.41ms ± 0%     2.72ms ± 0%   -57.48%   <====
Encoder_EncodeAllSimple4K/fastest-16    2.70µs ± 0%     2.56µs ± 0%    -5.26%
Encoder_EncodeAllSimple4K/default-16    33.1µs ± 0%     33.5µs ± 0%    +1.30%
Encoder_EncodeAllSimple4K/better-16     39.3µs ± 0%     38.8µs ± 0%    -1.12%
Encoder_EncodeAllSimple4K/best-16 …
```
> zstd: Improve "best" compression

- flate/deflate.go
- flate/deflate_test.go
- flate/fast_encoder.go
- flate/level1.go
- flate/level2.go
- flate/level3.go
- flate/level4.go
- flate/level5.go
- flate/level6.go
Use 5 byte hash instead of 4 byte hash.
This improves compression in most cases and will also yield faster decompression. Little to no performance impact.
Before/after:
```
file	out	level	insize	outsize	millis
nyc-taxi-data-10M.csv	gzkp	1	3325605752	922273214	14065	225.49
nyc-taxi-data-10M.csv	gzkp	1	3325605752	846471964	14342	221.12
nyc-taxi-data-10M.csv	gzkp	2	3325605752	883782053	15683	202.22
nyc-taxi-data-10M.csv	gzkp	2	3325605752	815766227	14865	213.35
nyc-taxi-data-10M.csv	gzkp	3	3325605752	878726683	17308	183.24
nyc-taxi-data-10M.csv	gzkp	3	3325605752	808448239	16882	187.86
nyc-taxi-data-10M.csv	gzkp	4	3325605752	789447233	20651	153.57
nyc-taxi-data-10M.csv	gzkp	4	3325605752	789447233	20657	153.53
file	out	level	insize	outsize	millis	mb/s
enwik9	gzkp	1	1000000000	382781160	5713 …
```
> flate: Improve level 1-3 compression

- gzhttp/compress.go
- gzhttp/compress_test.go
Also when it cannot be gzipped.
> gzhttp: Always delete `HeaderNoCompression`

- zstd/encoder.go
- zstd/encoder_test.go
- zstd/fuzz_test.go
Adds function that will return the expected maximum size of a given input size with current settings.
See #688
> zstd: Add MaxEncodedSize to encoder

- zstd/enc_best.go
Check "best" end-of-match offset further forward.
Missed bytes are picked up later.
nyc-taxi-data: 474949772 -> 469436962
silesia: 60073508 -> 59993313
> zstd: Improve "best" end search

- zstd/decodeheader.go
- zstd/dict.go
- zstd/framedec.go
This replaces some bytes.Equal calls, which compile down to calls to runtime.memequal, with uint32 or string comparisons that become CMPL instructions (or a series of CMPBs, in one case).
The code is several dozen instructions shorter. Benchmarks show no regressions:
```
name                                                  old speed      new speed      delta
Decoder_DecoderSmall/kppkn.gtb.zst/buffered-8          459MB/s ± 0%   458MB/s ± 0%    ~     (p=0.546 n=9+9)
Decoder_DecoderSmall/kppkn.gtb.zst/unbuffered-8        566MB/s ± 3%   568MB/s ± 2%    ~     (p=0.481 n=10+10)
Decoder_DecoderSmall/geo.protodata.zst/buffered-8     1.19GB/s ± 0%  1.19GB/s ± 0%  +0.24%  (p=0.040 n=9+9)
Decoder_DecoderSmall/geo.protodata.zst/unbuffered-8    831MB/s ± 2%   832MB/s ± 2%    ~     (p=0.853 n=10+10) …
```
> zstd: Replace bytes.Equal with smaller comparisons

- zstd/blockdec.go
- zstd/decoder.go
Two patches:
* check ignoreChecksum once in Decoder.nextBlock and skip the final bit of computation when it's not needed (restic uses zstd without CRC)
* do the actual check a bit faster and save some allocations by storing the CRC as a uint32 instead of a slice
See second commit for benchmark figures.
> zstd: Faster CRC checking/skipping

- zstd/enc_best.go
Lifted ofCode and mlCode computations out of match.estBits, so that method will be inlined into its only caller. Also some changes to eliminate a branch: the last if block becomes two CMOVs/CSELs on amd64 and arm64.
name                              old speed      new speed       delta
Encoder_EncodeAllSimple/best-8    11.1MB/s ± 1%   16.9MB/s ± 1%  +52.23%  (p=0.000 n=10+10)
Encoder_EncodeAllSimple4K/best-8  8.41MB/s ± 1%  10.95MB/s ± 0%  +30.20%  (p=0.000 n=10+10)
name                              old alloc/op   new alloc/op    delta
Encoder_EncodeAllSimple/best-8       20.0B ± 0%      18.0B ± 0%  -10.00%  (p=0.002 n=8+10)
Encoder_EncodeAllSimple4K/best-8     2.00B ± 0%      2.00B ± 0%     ~     (all equal)
> zstd: Improve throughput of SpeedBestCompression encoder

- zstd/enc_best.go
This reverts commit 2878205bda99754286840d77f1d27331374f5e3a.
Turns out that the speedup was due to a bug. In:
offset := uint32(m.rep)
if offset < 0 {
offset = uint32(m.s-m.offset) + 3
}
offset is never < 0 because it's cast to uint32 too early.
Sorry about this.
> zstd: Revert #699

- zstd/enc_base.go
- zstd/zstd.go
- zstd/zstd_test.go
Another attempt to get the "best" encoder to run faster. This time, I added tests and did some sanity checks. The code is a bit shorter because I merged two identical functions into one. (There's a nearly identical matchLen function in the flate package; you might want to consider moving it to an internal package.)
```
name                                 old speed      new speed      delta
Encoder_EncodeAllXML-8                284MB/s ± 1%   283MB/s ± 1%  -0.28%  (p=0.004 n=19+20)
Encoder_EncodeAllSimple/fastest-8     111MB/s ± 0%   112MB/s ± 1%  +0.95%  (p=0.000 n=17+19)
Encoder_EncodeAllSimple/default-8    78.2MB/s ± 1%  77.8MB/s ± 0%  -0.47%  (p=0.000 n=20+19)
Encoder_EncodeAllSimple/better-8     65.6MB/s ± 1%  65.7MB/s ± 1%    ~     (p=0.189 n=20+20)
Encoder_EncodeAllSimple/best-8 …
```
> zstd: Rewrite matchLen to make it inlineable

- zstd/enc_best.go
- zstd/enc_better.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
Benchmark results on amd64 below. These do not take into account #701. They're for Go 1.19; Go 1.20 produces slightly better asm for the old code, but still produces pretty bad asm, esp. on 32-bit platforms.
See also golang/go#56954.
```
name                                 old speed      new speed       delta
Encoder_EncodeAllXML-8                283MB/s ± 1%    284MB/s ± 0%     ~     (p=0.026 n=30+20)
Encoder_EncodeAllSimple/fastest-8     111MB/s ± 0%    111MB/s ± 1%     ~     (p=0.011 n=28+20)
Encoder_EncodeAllSimple/default-8    78.4MB/s ± 1%   78.3MB/s ± 1%     ~     (p=0.572 n=30+19)
Encoder_EncodeAllSimple/better-8     65.9MB/s ± 1%   66.2MB/s ± 1%   +0.53%  (p=0.009 n=30+20)
Encoder_EncodeAllSimple/best-8       11.1MB/s ± 1%   11.6MB/s ± 3%   +4.42%  (p=0.000 n=27+28) …
```
> zstd: Write table clearing in a way that the compiler recognizes

- zstd/enc_base.go
- zstd/enc_best.go
- zstd/enc_better.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
- zstd/encoder_options.go
- zstd/fuzz_test.go
- zstd/zstd.go
Instead of setting the limit to the largest window size, set it to the chosen one.
Mainly faster on small independent encodes:
```
λ benchcmp before.txt after.txt
benchmark                                         old ns/op     new ns/op     delta
BenchmarkEncoder_EncodeAllSimple4K/fastest-32     3145          3133          -0.38%
BenchmarkEncoder_EncodeAllSimple4K/default-32     41485         40624         -2.08%
BenchmarkEncoder_EncodeAllSimple4K/better-32      49352         49197         -0.31%
BenchmarkEncoder_EncodeAllSimple4K/best-32        421522        407392        -3.35%
benchmark                                         old MB/s     new MB/s     speedup
BenchmarkEncoder_EncodeAllSimple4K/fastest-32     1302.48      1307.39      1.00x
BenchmarkEncoder_EncodeAllSimple4K/default-32 …
```
> zstd: Use individual reset threshold

- huff0/compress.go
v == 0 implies v <= m, so we can skip a CMOV in that case. Benchmarks show a tiny gain on most inputs and a large gain on the few with very small alphabets:
```
name                                      old speed      new speed       delta
Compress1XReuseNone/digits-8               432MB/s ± 1%    434MB/s ± 1%     ~     (p=0.023 n=14+35)
Compress1XReuseNone/gettysburg-8           241MB/s ± 1%    242MB/s ± 1%   +0.58%  (p=0.000 n=14+34)
Compress1XReuseNone/twain-8                352MB/s ± 1%    354MB/s ± 1%   +0.62%  (p=0.000 n=14+29)
Compress1XReuseNone/low-ent.10k-8          460MB/s ± 2%    464MB/s ± 1%   +0.92%  (p=0.000 n=14+30)
Compress1XReuseNone/superlow-ent-10k-8     304MB/s ± 1%    305MB/s ± 1%     ~     (p=0.040 n=15+33)
Compress1XReuseNone/crash2-8              10.6MB/s ± 1% …
```
> huff0: Check for zeros earlier in Scratch.countSimple

- zstd/enc_best.go
The best encoder selects matches based on the criterion
a.est+(a.s-b.s)*bitsPerByte>>10 < b.est+(b.s-a.s)*bitsPerByte>>10
If this were computed on the reals, it would be equivalent to a.est < b.est, so the added terms only capture round-off error (this is also why CSE doesn't eliminate them).
Changing the formula to
a.est-b.est+(a.s-b.s)*bitsPerByte>>10 < 0
captures the intention better, I think, and improves compression:
enwik9           260989017 259699309 -0.4942%
silesia/dickens    3233958   3222189 -0.3639%
silesia/mozilla   16980973  16912341 -0.4042%
silesia/mr         3505223   3505553  0.0094%
silesia/nci        2313702   2289871 -1.0300%
silesia/ooffice    2915199   2896410 -0.6445%
silesia/osdb       3364752   3390871  0.7763%
silesia/reymont    1658404   1656006 -0.1446% …
> zstd: Improve best compression's match selection

- zstd/enc_best.go
```
name                              old speed      new speed      delta
Encoder_EncodeAllSimple/best-8    12.2MB/s ± 1%  15.3MB/s ± 2%  +25.31%  (p=0.000 n=20+19)
Encoder_EncodeAllSimple4K/best-8  10.5MB/s ± 1%  12.9MB/s ± 0%  +23.03%  (p=0.000 n=20+17)
name                              old alloc/op   new alloc/op   delta
Encoder_EncodeAllSimple/best-8       18.0B ± 0%     14.0B ± 0%  -22.22%  (p=0.000 n=18+20)
Encoder_EncodeAllSimple4K/best-8     1.00B ± 0%     1.00B ± 0%     ~     (all equal)
```
Output sizes for enwik9 and Silesia corpus are unchanged.
> zstd: Select best match using selection trees

- zstd/internal/xxhash/xxhash_arm64.s
Syncs with https://github.com/cespare/xxhash/pull/51
> zstd: sync xxhash with final accepted patch upstream

- zstd/internal/xxhash/README.md
- zstd/internal/xxhash/xxhash.go
- zstd/internal/xxhash/xxhash_amd64.s
- zstd/internal/xxhash/xxhash_arm64.s
- zstd/internal/xxhash/xxhash_asm.go
- zstd/internal/xxhash/xxhash_other.go
- zstd/internal/xxhash/xxhash_test.go
Unsafe parts omitted, noasm build tag added back in.
> zstd: Import xxhash v2.2.0

- .github/workflows/go.yml
- .github/workflows/release.yml
- .goreleaser.yml
- flate/stateless.go
Don't re-alloc and copy dict for every block when compressing more than 32KB.
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkEncodeDigitsSL1e4-32     52954         52850         -0.20%
BenchmarkEncodeDigitsSL1e5-32     781061        745420        -4.56%
BenchmarkEncodeDigitsSL1e6-32     8143640       7715674       -5.26%
BenchmarkEncodeTwainSL1e4-32      68150         68415         +0.39%
BenchmarkEncodeTwainSL1e5-32      715140        687326        -3.89%
BenchmarkEncodeTwainSL1e6-32      7718175       7339694       -4.90%
benchmark                         old MB/s     new MB/s     speedup
BenchmarkEncodeDigitsSL1e4-32     188.84       189.21       1.00x
BenchmarkEncodeDigitsSL1e5-32     128.03       134.15       1.05x
BenchmarkEncodeDigitsSL1e6-32 …
```
> flate: Improve speed in big stateless blocks.

- zstd/decodeheader.go
- zstd/framedec.go
This patches reduces the number of bounds checks in zstd, as reported by
go build -gcflags="-d=ssa/check_bce/debug=1" |& wc -l
from 723 to 693.
> zstd: Trigger BCE by switching on lengths

- zstd/_generate/gen.go
- zstd/seqdec_amd64.s
These are all in return sequences, so no performance gain expected, but the generated code is smaller.
> zstd: Shave some instructions off the amd64 asm

- s2/decode.go
- s2/index_test.go
> s2: Add example for indexing and existing stream

- zstd/encoder_test.go
- zstd/snappy_test.go
I think the GC will clean these up, but you don't want it doing that in the middle of a benchmark run.
> tests: Don't leak file descriptors in tests

- huff0/bitreader.go
Apparently, Go 1.19 understands that v := b.in[b.off-4 : b.off] has length four, but then inserts an additional check for v = v[:4]. Removing the latter ensures the comments saying "2 bounds checks" are correct again (two checks in a single line).
> huff0: Reduce bounds checking

- huff0/_generate/gen.go
- huff0/decompress_amd64.s
Main changes:
* Compute out[id * dstEvery + i] statically. This shaves four instructions off the main loops. (It also frees up a register.)
* Track "exhausted" by addition instead or OR. This gets rid of an additional instruction. The variable is now also zeroed inside the loop as a dependency hint.
Benchmark results show small speedups on some datasets:
```
name                                           old speed      new speed      delta
Decompress1XTable/digits-8                      350MB/s ± 0%   350MB/s ± 1%    ~     (p=0.764 n=10+9)
Decompress1XTable/gettysburg-8                  270MB/s ± 1%   268MB/s ± 1%  -0.72%  (p=0.001 n=10+10)
Decompress1XTable/twain-8                       329MB/s ± 1%   328MB/s ± 0%    ~     (p=0.035 n=10+9)
Decompress1XTable/low-ent.10k-8 …
```
> huff0: Assembler improvements

- gzhttp/compress.go
- gzhttp/compress_test.go
I've been enjoying using compress/gzhttp as a drop in replacement for NYTimes's gzip middleware, so thanks for your effort here!
In a current project I'm looking to start using [ETag headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) for cache revalidation, and discovered that there's a few complicated implementation details that arise when combining ETags and content negotiation.  Notably, [RFC 7232 Section 2.3.3](https://www.rfc-editor.org/rfc/rfc7232#section-2.3.3) explains with an example that an identical resource must have different ETags for compressed vs uncompressed versions. 
Due to the convenient fact that this middleware is completely transparent to my handlers (where ETags are set), unfortunately it's not currently possible to meet the specification's …
> Add SuffixETag() and DropETag() options to prevent ETag collisions on compressed responses

- go.mod
Officially retract old versions due to #503
Active Jan 11, 2022 -> Feb 22, 2022
> Retract v1.14.1-v.1.14.3

- zstd/blockdec.go
Credit to @greatroar for finding this.
Alternative to #721
> zstd: Don't allocate dataStorage when using byteBuf

- huff0/compress.go
This is ugly, but it forces the compiler to merge loads and stores of nodeElts.
```
name                                      old speed      new speed      delta
Compress4XReuseNone/digits-8               433MB/s ± 1%   434MB/s ± 0%     ~     (p=0.393 n=10+10)
Compress4XReuseNone/gettysburg-8           245MB/s ± 1%   254MB/s ± 1%   +3.55%  (p=0.000 n=10+10)
Compress4XReuseNone/twain-8                363MB/s ± 0%   363MB/s ± 0%     ~     (p=0.360 n=8+10)
Compress4XReuseNone/low-ent.10k-8          465MB/s ± 0%   467MB/s ± 0%   +0.32%  (p=0.008 n=9+10)
Compress4XReuseNone/superlow-ent-10k-8     305MB/s ± 2%   304MB/s ± 1%     ~     (p=0.143 n=10+10)
Compress4XReuseNone/case1-8               13.1MB/s ± 1%  14.6MB/s ± 2%  +11.44%  (p=0.000 n=10+10)
Compress4XReuseNone/case2-8 …
```
> huff0: Speed up compression of short blocks

- fse/compress.go
Two patches to increase compression speed. Details in the commit messages, combined effect:
```
name                     old speed      new speed      delta
Compress/gettysburg-8     181MB/s ± 1%   189MB/s ± 0%   +4.52%  (p=0.000 n=10+9)
Compress/digits-8         241MB/s ± 0%   251MB/s ± 1%   +4.09%  (p=0.000 n=9+9)
Compress/twain-8          218MB/s ± 0%   228MB/s ± 0%   +4.46%  (p=0.000 n=10+10)
Compress/low-ent-8        239MB/s ± 0%   244MB/s ± 1%   +1.89%  (p=0.000 n=10+10)
Compress/superlow-ent-8   208MB/s ± 1%   210MB/s ± 0%   +1.04%  (p=0.000 n=9+8)
Compress/endzerobits-8   11.5MB/s ± 1%  13.4MB/s ± 1%  +16.82%  (p=0.000 n=10+10)
Compress/pngdata.001-8    224MB/s ± 0%   225MB/s ± 1%   +0.79%  (p=0.000 n=8+9)
Compress/normcount2-8    35.7MB/s ± 1%  36.4MB/s ± 1%   +2.03%  (p=0.000 …
```
> fse: Optimize compression

- s2/cmd/_s2sx/_unpack/main.go
- s2/cmd/s2c/main.go
Use concurrent decoding when recompressing and verifying.
s2sx: Use concurrent decoding with single files (non-tar)
> s2c/s2sx: Use concurrent decoding

- s2/decode.go
- s2/encode_test.go
- s2/index_test.go
> s2: Support ReadAt in ReadSeeker

- internal/snapref/encode_other.go
- s2/encode.go
- s2/encode_test.go
```Go
// WriterCustomEncoder allows to override the encoder for blocks on the stream.
// The function must compress 'src' into 'dst' and return the bytes used in dst as an integer.
// Block size (initial varint) should not be added by the encoder.
// Returning value 0 indicates the block could not be compressed.
// The function should expect to be called concurrently.
func WriterCustomEncoder(fn func(dst, src []byte) int) WriterOption
```
> s2: Add support for custom stream encoder

- gzhttp/compress.go
- gzhttp/compress_test.go
- gzhttp/writer/gzkp/gzkp.go
- gzhttp/writer/gzstd/stdlib.go
- gzhttp/writer/interface.go
```
Before:
Benchmark2kJitter-32    	   55479	     21371 ns/op	  95.83 MB/s	    3575 B/op	      20 allocs/op
After:
Benchmark2kJitter-32    	   54948	     21599 ns/op	  94.82 MB/s	    3451 B/op	      16 allocs/op
```
Don't put too much into the speed. GC is not included. Most of the allocs are in `httptest.ResponseRecorder`.
> gzhttp: Remove a few unneeded allocs

- gzhttp/compress.go
rand.Reader.Read(p) is allowed to return < len(p) bytes and no error, and the Mac implementation sometimes does. I don't know if it will do that for len(p) == 4, but rand.Read is safer in any case.
This is a security fix. I'm sending it in the clear because it only affects an unreleased version of this library.
> gzhttp: Fix crypto/rand.Read usage

- gzhttp/README.md
- gzhttp/compress.go
- gzhttp/compress_test.go
The padding size is determined by the remainder of a CRC32 of the content.
Since the payload contains elements unknown to the attacker, there is no reason to believe they can derive any information from this remainder, or predict it.
However, for those that feel uncomfortable with a CRC32 being used for this can enable "paranoid" mode which will use SHA256 for determining the padding.
The hashing itself is about 2 orders of magnitude slower, but in overall terms will maybe only reduce speed by 10%.
Paranoid mode has no effect if buffer is < 0 (non-content aware padding).
2K payload roundtrip difference:
```
Benchmark2kJitter-32    	   67309	     17580 ns/op	 116.50 MB/s	    3478 B/op	      17 allocs/op
Benchmark2kJitterParanoid-32    	   54398	     21564 ns/op	  94.97 MB/s	    3438 B/op …
```
> gzhttp: Use SHA256 as paranoid option

- zstd/bytebuf.go
This method was inconsistent with its cousin readerWrapper.readBig in that it returned 0, nil when the input is too short.
I'm not sure what the effects of this inconsistency are, if any. I suppose nearly all suppressed errors would have been reported someplace else.
> zstd: Report EOF from byteBuf.readBig

- huff0/bitwriter.go
- huff0/compress.go
A specialized encFourSymbols produces better code than two inlined encTwoSymbols calls in a row. Its arguments need to be different to make the inlining work. Benchmark results on amd64:
```
name                                      old speed      new speed      delta
Compress1XReuseNone/digits-8               438MB/s ± 1%   461MB/s ± 1%   +5.18%  (p=0.000 n=10+9)
Compress1XReuseNone/gettysburg-8           254MB/s ± 1%   254MB/s ± 1%     ~     (p=0.412 n=10+9)
Compress1XReuseNone/twain-8                363MB/s ± 1%   367MB/s ± 0%   +1.05%  (p=0.000 n=10+10)
Compress1XReuseNone/low-ent.10k-8          466MB/s ± 0%   485MB/s ± 1%   +4.01%  (p=0.000 n=9+10)
Compress1XReuseNone/superlow-ent-10k-8     305MB/s ± 0%   313MB/s ± 1%   +2.49%  (p=0.000 n=8+9)
Compress1XReuseNone/crash2-8 …
```
> huff0: Speed up compress1xDo

- zstd/fuzz_test.go
Only report mismatches in nil state, and make that an error.
> tests: Remove fuzz printing

- zstd/enc_best.go
```
name                              old speed      new speed      delta
Encoder_EncodeAllSimple/best-8    14.8MB/s ± 3%  20.7MB/s ± 3%   +39.53%  (p=0.000 n=17+19)
Encoder_EncodeAllSimple4K/best-8  11.8MB/s ± 1%  19.2MB/s ± 6%   +62.17%  (p=0.000 n=20+20)
name                              old alloc/op   new alloc/op   delta
Encoder_EncodeAllSimple/best-8       14.0B ± 0%     10.2B ± 8%   -27.07%  (p=0.000 n=16+19)
Encoder_EncodeAllSimple4K/best-8     1.00B ± 0%     0.00B       -100.00%  (p=0.000 n=20+19)
```
Also, compressing enwik9 takes 6.375% less wall clock time.
Output from silesia corpus and enwik9 is about .05% bigger, due to the different order in which comparisons are done:
```
dickens    3222189    3220994 (× 0.99963)
enwik9   259699309  259846164 (× 1.00057)
mozilla …
```
> zstd: Speed up + improve best encoder

- s2/_generate/gen.go
- s2/encode.go
- s2/encode_test.go
- s2/encodeblock_amd64.s
- s2/s2_test.go
Fixes crash on encoding single blocks close to or above 2147483647 bytes on amd64.
Fixes #778
Use unsigned compares in assembly.
Lowers the maximum block size on 32 bit platforms. Realistically you wouldn't be able to get close to it anyway.
> s2: Fix huge block overflow

- zstd/zstd.go
load3232 and load6432 now limit their slice to its length. This improves safety, since encoders can no longer look at the part beyond the length. It also produces several dozen fewer instructions for bounds checks.
> zstd: Make load(32|64)32 safer and smaller

- .github/workflows/go.yml
- zstd/enc_best.go
- zstd/fuzz_test.go
- zstd/zstd_test.go
When m.s was extended far back we could read out of bounds.
Fixes #786
Re-enables accidentally disabled fuzz tests.
> zstd: Fix quick reject on long backmatches

- zstd/blockenc.go
- zstd/encoder.go
- zstd/encoder_options.go
With no sequences (matches) literal compression was turned off.
Re-enable this and simplify code. Set as default for "Better" and "Best".
> zstd: Respect WithAllLitEntropyCompression

- zstd/enc_best.go
There were four places were this value was loaded: before the loop, at the end, and before two continues. Doing it at the start reduces the code size. It also seems to give a tiny speedup:
```
name                              old speed      new speed      delta
Encoder_EncodeAllSimple/best-8    16.8MB/s ± 2%  16.9MB/s ± 1%  +0.47%  (p=0.025 n=8+10)
Encoder_EncodeAllSimple4K/best-8  16.0MB/s ± 2%  16.2MB/s ± 1%  +1.67%  (p=0.000 n=10+10)
name                              old alloc/op   new alloc/op   delta
Encoder_EncodeAllSimple/best-8       19.0B ± 5%     18.0B ± 0%  -5.26%  (p=0.002 n=9+9)
Encoder_EncodeAllSimple4K/best-8     1.00B ± 0%     1.00B ± 0%    ~     (all equal)
```
> zstd: Load source value at start of loop

- zstd/decoder.go
- zstd/framedec.go
frameDec.consumeCRC is now inlineable. Its callers already check for ignoreChecksum. frameDec.checkCRC's callers already check for HasCheckSum and ignoreChecksum.
xxhash.Digest.Write is documented as always returning len(b), nil, so no need to check its return values.
> zstd: Shorten checksum code

- gzhttp/compress.go
Sometimes users will want to use the `http.Flusher`, or `http.Hijacker`, etc. interfaces from an `http.ResponseWriter`, which `gzhttp.ResponseWriter` does not implement but the underlying one does.
It is common to provide an `Unwrap` function to access it, for example the standard library expects that (although I didn't find any official documentation on it). See [http.ResponseController](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/net/http/responsecontroller.go;l=41-43) for example.
> Allow access to internal ResponseWriter in gzhttp handler

- zstd/bytebuf.go
- zstd/decoder_test.go
This fixes an "unexpected EOF" error that can occur when streaming from a network source into the zstd decompressor. I maintain a production system which streams zstd-compressed data from AWS S3 that hits this bug regularly when under heavy load.
Even when asking for one byte of data, it's necessary to use io.ReadFull. It's valid to return 0 bytes without EOF on a read, and this behavior is seen on network sources rather frequently.
I wrote up a test that reproduces the bug here:
https://github.com/jnoxon/zstd-zero-length-read-bug
> readerWrapper: readByte needs to use io.ReadFull

- gzip/gunzip.go
- gzip/gunzip_test.go
Fix checksum calculation in `WriteTo` after something has been read from the stream.
Fixes #803
> gzip: Fix WriterTo after initial read

- SECURITY.md
Closes #809
I've created the SECURITY.md file following a GitHub's template and considering the [report vulnerability through security advisory](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability), which is a handy new GitHub feature still in beta, but has to be enabled.
If you're interested in this feature, it must be activated for the repository:
1. Click on this [link](https://github.com/klaupost/compress/settings/security_analysis) to go to Code security & analysis section on your repo's settings
2. Click "Enable" for "Private vulnerability reporting (Beta)"
If you rather not use this feature, you can also request users to report vulnerabilities to an email. If that's the case, let me know which …
> Add a Security-Policy

- zstd/README.md
The example would otherwise give a `undefined: WithDecoderConcurrency`
> docs: Fix undefined WithDecoderConcurrency

- zstd/blockdec.go
- zstd/matchlen_amd64.go
- zstd/matchlen_amd64.s
- zstd/matchlen_generic.go
- zstd/zstd.go
Copied from the S2 implementation. 5-10% faster.
(Potentially) Replaces #823
> zstd: Add amd64 match length assembly

- zstd/dict_test.go
- zstd/enc_base.go
- zstd/enc_dfast.go
- zstd/enc_fast.go
Fix `allDirty` not being set correctly on first encode, meaning lookup table was not copied.
This would cause first encode only to use partial dictionary lookups.
Fixes #828
> zstd: Fix default level first dictionary encode

- s2/reader.go
Add GetBufferCapacity() method. We are reusing readers with sync.Pool and we'd like to avoid allocating memory for the default block size since most of the inputs are smaller. To have a better estimate of how big the lazy buffer should be, we are thinking about keeping in mind a running average of the internal buffer capacities. This method would allow us to implement that.
> s2: add GetBufferCapacity() method

- .github/workflows/go.yml
- flate/fast_encoder.go
- flate/matchlen_amd64.go
- flate/matchlen_amd64.s
- flate/matchlen_generic.go
A few percent faster.
```
before:
github-june-2days-2019.json	gzkp	1	6273951764	1073607045	17271	346.43
github-june-2days-2019.json	gzkp	2	6273951764	1045461954	20016	298.92
github-june-2days-2019.json	gzkp	3	6273951764	1030139729	21372	279.95
github-june-2days-2019.json	gzkp	4	6273951764	992526317	26354	227.03
github-june-2days-2019.json	gzkp	5	6273951764	938015731	28919	206.89
github-june-2days-2019.json	gzkp	6	6273951764	918717756	32473	184.25
github-june-2days-2019.json	gzkp	7	6273951764	924473679	41597	143.84
github-june-2days-2019.json	gzkp	8	6273951764	905294390	52419	114.14
github-june-2days-2019.json	gzkp	9	6273951764	895561157	103132	58.02
after:
github-june-2days-2019.json	gzkp	1	6273951764	1073607045	16978	352.40
github-june-2days-2019.json	gzkp	2	6273951764	1045461954	19362 …
```
> flate: Add amd64 assembly matchlen

- s2/_generate/gen.go
- s2/encodeblock_amd64.s
Mainly faster on long matches, but has little to no regression on short matches.
```
λ s2c -cpu=1 --bench=5 \compress\github-june-2days-2019.json
BEFORE: Compressing... 6273951764 -> 944876986 [15.06%]; 9.43s, 634.5MB/s
AFTER:  Compressing... 6273951764 -> 944876986 [15.06%]; 9.269s, 645.5MB/s
λ s2c -cpu=1 --bench=5 \compress\nyc-taxi-data-10M.csv
BEFORE: Compressing... 3325605752 -> 884713054 [26.60%]; 8.296s, 382.3MB/s
AFTER:  Compressing... 3325605752 -> 884713054 [26.60%]; 8.173s, 388.1MB/s
λ s2c -cpu=1 --bench=5 \compress\enwik9
BEFORE: Compressing... 1000000000 -> 416582393 [41.66%]; 3.706s, 257.3MB/s
AFTER:  Compressing... 1000000000 -> 416582393 [41.66%]; 3.636s, 262.3MB/s
```
> s2: Do 2 overlapping match checks

- flate/fuzz_test.go
```
t.Run() is not supported when fuzzing in libFuzzer mode
testing.(*T).Run
```
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61356
> tests: Fix OSS fuzzer t.Run

- zstd/_generate/gen.go
- zstd/bitreader.go
- zstd/seqdec.go
- zstd/seqdec_amd64.s
- zstd/seqdec_generic.go
We can reslice instead of keeping a separate offset. This gets rid of some bounds checks. Also some other micro-optimizations to bit reading code. Combined results:
```
│   zstd/old   │              zstd/new               │
│     B/s      │     B/s       vs base               │
Decoder_DecoderSmall/kppkn.gtb.zst/buffered-8          427.6Mi ± 0%   428.2Mi ± 0%  +0.13% (p=0.019 n=10)
Decoder_DecoderSmall/kppkn.gtb.zst/unbuffered-8        511.6Mi ± 3%   516.9Mi ± 3%       ~ (p=0.280 n=10)
Decoder_DecoderSmall/geo.protodata.zst/buffered-8      1.110Gi ± 0%   1.110Gi ± 0%       ~ (p=0.165 n=10)
Decoder_DecoderSmall/geo.protodata.zst/unbuffered-8    824.7Mi ± 2%   827.3Mi ± 2%       ~ (p=0.481 n=10)
Decoder_DecoderSmall/plrabn12.txt.zst/buffered-8       330.4Mi ± 0%   330.3Mi ± 1%       ~ …
```
> zstd: Remove offset from bitReader

- dict/README.md
- dict/builder.go
- dict/cmd/builddict/main.go
- s2/dict.go
- zstd/blockenc.go
- zstd/dict.go
This is an *experimental* dictionary builder for Zstandard, S2, LZ4 and more.
This diverges from the Zstandard dictionary builder, and may have some failure scenarios for very small or uniform inputs.
Dictionaries returned should all be valid, but if very little data is supplied, it may not be able to generate a dictionary.
With a large, diverse sample set, it will generate a dictionary that can compete with the Zstandard dictionary builder,
but for very similar data it will not be able to generate a dictionary that is as good.
Feedback is welcome.
First of all a collection of *samples* must be collected.
These samples should be representative of the input data and should not contain any complete duplicates.
Only the *beginning* of the samples is important, the rest can be truncated. …
> Add dictionary builder

- gzip/gunzip.go
The code already checks to see if the buffer can be reused, but since it's not copied in the overwrite, a new buffer is allocated each time.
> gzip: Copy bufio.Reader on Reset

- s2/encode.go
- s2/encode_go.go
- s2/s2_test.go
Fixes `panic: runtime error: index out of range [7] with length 5` when providing short input to EstimateBlockSize.
Found via #866
> s2: Fix EstimateBlockSize on 6&7 length input

- flate/_gen/gen_inflate.go
- flate/inflate.go
- flate/inflate_gen.go
- flate/reader_test.go
- `decompressor.step` is now enumeric instead of function pointer. This reduces ALL allocations in decompressor benchmarks to constant 1 (previously this number differed for each case). However, it doesn't bring much gains in terms of throughtput.
- `huffmanBlockDecoder()`, generated by _gen/gen_inflate.go, also used to return a function pointer. Now calling the method directly inside of it. Also doesn't bring much gains, but in microbenchmarks may be visible
- Improved decompressor benchmarks by replacing io.Copy() with io.CopyBuffer(), because io.Copy() allocates internally a buffer for reading
- Removed some expressions, that are useless
> Reduce allocations in flate decompressor and minor code improvements

- zstd/enc_best.go
- zstd/enc_better.go
* Improve filling of hash table.
* Improve bit estimate precision.
```
nyc-taxi-data-10M.csv:  459777201 -> 458477504
github-ranks-backup.bin: 375643363 -> 370855760
enwik9: 257093205 -> 256671305
apache.log: 110308693 -> 109832224
github-june-2days-2019.json 458742026 -> 457306131
```
0.02 -> 0.3% improvement observed (input -> output size difference - relative output is bigger)
> zstd: Improve better/best compression

- gzhttp/compress.go
- gzhttp/compress_test.go
If compression had not yet been triggered in Write, be sure to detect content type on Close.
Fixes #882
> gzhttp: Fix missing content type on Close

- huff0/compress.go
The body of the first loop in countSimple contained an explicit nil check. Lift that out of the loop for some extra throughput:
goos: linux
goarch: amd64
pkg: github.com/klauspost/compress/huff0
cpu: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
│  huff0/old   │           huff0/nilcheck            │
│     B/s      │     B/s       vs base               │
Compress1XReuseNone/digits-8               438.9Mi ± 0%   467.7Mi ± 1%   +6.55% (p=0.002 n=6)
Compress1XReuseNone/gettysburg-8           247.3Mi ± 2%   257.4Mi ± 1%   +4.08% (p=0.002 n=6)
Compress1XReuseNone/twain-8                349.2Mi ± 1%   367.9Mi ± 1%   +5.35% (p=0.002 n=6)
Compress1XReuseNone/low-ent.10k-8          474.3Mi ± 1%   488.4Mi ± 0%   +2.98% (p=0.002 n=6)
Compress1XReuseNone/superlow-ent-10k-8     303.4Mi ± 1%   341.6Mi ± 0% …
> huff0: Speed up symbol counting

- gzip/gunzip.go
- gzip/gunzip_test.go
RFC 1952 states: Reserved FLG bits must be zero.
> gzip: Error out if reserved bits are set

- zstd/_generate/gen.go
- zstd/seqdec_amd64.s
The asm needs to compute decSymbol.newState, which is
uint16(state >> 16),
or, equivalently (except for types),
uint32(state) >> 16.
This can be accomplished by a MOVL+SHRL, the former of which is elided by avo, so we get a single instruction for both the BMI2 and non-BMI2 cases.
Benchmarks show no difference on a new BMI2-supporting machine, but on an older i7, decompression throughput is a tiny bit better:
goos: linux
goarch: amd64
pkg: github.com/klauspost/compress/zstd
cpu: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
│     old      │                shift                │
│     B/s      │     B/s       vs base               │
Decoder_DecodeAll/kppkn.gtb.zst-8        441.4Mi ± 2%   450.4Mi ± 0%  +2.03% (p=0.000 n=10)
Decoder_DecodeAll/geo.protodata.zst-8    1.148Gi ± 1%   1.152Gi ± 0% …
> zstd: Shorter and faster asm for decSymbol.newState

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
Closes #898
As mentioned on the issue, this PR enhances project security by hash-pinning the dependencies that are called under dangerous permissions. Additionally, it enables dependabot to update them automatically.
I configured dependabot in a way that all of version updates will be collapsed in a single PR sent monthly -- this avoids noisy PRs, which is a common concern haha. Regardless of the frequency chosen, for the case of security updates a PR with the fixed version would be sent right away.
> CI: Hash pin sensitive actions and configure Dependabot to automatically update them

- internal/race/norace.go
- internal/race/race.go
- s2/decode.go
- s2/encode_amd64.go
- s2/s2.go
- s2/writer.go
Assembly code isn't instrumented with race detector. This adds few annotations for race detector.
> internal/race,s2: add some race instrumentation

- zstd/decodeheader.go
- zstd/frameenc.go
Allows to remove the frame header from input and adds a function that encodes current frame header values.
New API:
```Go
// DecodeAndStrip will decode the header from the beginning of the stream
// and on success return the remaining bytes.
// This will decode the frame header and the first block header if enough bytes are provided.
// It is recommended to provide at least HeaderMaxSize bytes.
// If the frame header cannot be read an error will be returned.
// If there isn't enough input, io.ErrUnexpectedEOF is returned.
// The FirstBlock.OK will indicate if enough information was available to decode the first block header.
func (h *Header) DecodeAndStrip(in []byte) (remain []byte, err error)
// AppendTo will append the encoded header to the dst slice.
// There is no error checking …
```
> zstd: Add Frame header encoding and stripping

- zstd/fse_decoder_generic.go
Benchmark results below. On a different machine, I saw somewhat bigger speedups when benchmarking a version that has the noasm version of FSE, but asm seqdec. The paper-100k benchmarks have some extreme variance in the first 12 runs, so I did 12 more to get a more reliable average. The apparent regression on that benchmark may be a fluke.
The asm FSE decoder still wins.
```
goos: linux
goarch: amd64
pkg: github.com/klauspost/compress/zstd
cpu: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
│     old      │                 new                 │
│     B/s      │     B/s       vs base               │
Decoder_DecoderSmall/kppkn.gtb.zst/buffered-8          252.3Mi ± 0%   251.9Mi ± 0%  -0.12% (p=0.027 n=12)
Decoder_DecoderSmall/kppkn.gtb.zst/unbuffered-8        300.2Mi ± 1%   299.5Mi ± 1%       ~ …
```
> zstd: Tweak noasm FSE decoder

- flate/deflate.go
- flate/deflate_test.go
Dictionary was being ignored when compressing with a custom window size.
Fixes #911
> flate: Fix reset with dictionary on custom window encodes

- s2/reader.go
The spec writes that 0xfe must not be interpreted by decompressors, so setting up a callback should be denied.
I left 0xfe open for use by the Writer, as it could maybe be valid for a user to handle padding manually.
> s2: Fix callbacks for skippable blocks and disallow 0xfe (Padding) for custom use

- s2/writer.go
My use case is to transfer a large compressed S2 stream with a few changes very often. To get a small diff I want to end blocks at application decided points rather than at byte offsets. This allows me to remove the first byte without every single block changing.
Flush() works for this, but it limits concurrency because it waits for the last block to be compressed rather than allowing that asynchronously.
So I'd like to propose AsyncFlush, which flushes the buffer to a block, but doesn't flush the block to the io.Writer.
There were actually a few places in the s2 code that also wanted to end the block, but didn't necessary want to flush to the writer.
> s2: Add AsyncFlush method: Complete the block without flushing

- s2/_generate/gen.go
- s2/encode_all.go
- s2/encodeblock_amd64.s
> s2: Fix literal+repeat exceeds dst

- zstd/decoder.go
Trivial typo found while reading the docs :)
> doc: Remove an excess word in a documentation comment

- internal/fuzz/helpers.go
- ossfuzz/ossfuzz.sh
No idea if this is supposed to go before or after the error check.
> ci: Remove sed for internal/fuzz/helpers.go

- zstd/blockenc.go
- zstd/enc_best.go
- zstd/enc_better.go
- zstd/encoder_test.go
Add full block RLE encoding.
Fastest+Default: The first block in RLE will be detected automatically, but following will likely be backreferences.
Better+Best: Explicit RLE block detection. Will always be encoded as RLE blocks.
Full block RLE are very uncommon and the gains are small, but can happen in very sparse data, so makes sense for "stronger" settings.
Add feature https://github.com/klauspost/compress/discussions/937
> zstd: Add RLE detection+encoding

- s2/index.go
- s2/s2.go
- s2/writer.go
- s2/writer_test.go
Only functional change is to add minimum 1MB between entries (which was enforced when saving anyway).
Probably close to a worst case (and probably noisy), but overall looks good:
```
benchmark                                                old ns/op     new ns/op     delta
BenchmarkReadFromRandom/default-c1-4k-win-32             4157177       2604339       -37.35%
BenchmarkReadFromRandom/default-c2-32                    788147        679660        -13.76%
BenchmarkReadFromRandom/best-c2-4k-win-32                215513740     207505150     -3.72%
BenchmarkReadFromRandom/default-c2-4k-win-32             8712437       8354241       -4.11%
BenchmarkReadFromRandom/better-c1-32                     2861139       1862028       -34.92%
BenchmarkReadFromRandom/none-c1-32 …
```
> s2: Reduce ReadFrom temporary allocations

- flate/matchlen_amd64.s
- zstd/matchlen_amd64.s
I only ran a few benchmarks and did not see a speedup, but the code is a bit shorter.
> flate, zstd: Shave some bytes off amd64 matchLen

- zstd/dict.go
We cannot build a useable table if RLE. Add a fake entry to generate valid tables.
Invalid offsets could be generated.
Fixes #950
> zstd: BuildDict fails with RLE table

- gzhttp/compress.go
- gzhttp/compress_go119.go
- gzhttp/compress_go120.go
- gzhttp/compress_test.go
- gzhttp/transport.go
- gzhttp/transport_test.go
TransportAlwaysDecompress will always decompress the response, regardless of whether we requested it or not.
Default is false, which will pass compressed data through if we did not request compression.
Replaces #977
Bonus: Remove code for Go 1.19 and older.
> gzhttp: Add TransportAlwaysDecompress option.

- dict/README.md
Confused me a bit when trying to install builddict
> docs: Fix URL typo when installing builddict

- s2/writer.go
- s2/writer_test.go
WriterBufferDone will perform a callback when EncodeBuffer has finished writing a buffer to the output and the buffer can safely be reused.
If the buffer was split into several blocks, it will be sent after the last block.
Callbacks will not be done concurrently.
Fixes #981
> s2: Add EncodeBuffer buffer recycling callback

- gzhttp/compress.go
- gzhttp/compress_test.go
Add new feature from discussions https://github.com/klauspost/compress/discussions/1001
> [gzhttp] Add supported decompress request body
